#!/usr/bin/env python3
"""Generate advanced dungeon definitions and their image specification document."""

from __future__ import annotations

import json
import math
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "js/definitions/advanced-dungeon-catalog.json"
CONTENT_PATH = ROOT / "js/definitions/advanced-dungeon-content.js"
DOC_PATH = ROOT / "Doc/追加ダンジョン画像仕様一覧.md"
PROMPT_DIR = ROOT / "Doc/追加ダンジョン5x5画像生成プロンプト"

ELEMENT_LABELS = {
    "fire": "炎",
    "water": "水",
    "grass": "草",
    "ice": "氷",
    "thunder": "雷",
    "wind": "風",
    "earth": "土",
    "light": "光",
    "dark": "闇",
}
AILMENTS = {"poison", "burn", "paralysis", "sleep", "confusion", "curse", "blind", "silence"}
PRESSURE_TYPES = {
    "astral_acceleration",
    "infernal_rebirth",
    "dragon_dominion",
    "demon_command",
    "lunar_eclipse",
    "storm_rule",
    "labyrinth_inversion",
    "time_stop",
    "law_collapse",
}
BEHAVIORS = {
    "empower",
    "atb_drain",
    "sweep",
    "multi_hit",
    "dispel_break",
    "drain",
    "execute",
    "commander",
    "boss",
}
MECHANICS = {
    "astral_fate",
    "infernal_fury",
    "dragon_blood",
    "demon_siege",
    "lunar_mirror",
    "storm_momentum",
    "labyrinth_dread",
    "time_erosion",
    "subspace_distortion",
}
UNIQUE_SKILL_TYPES = {
    "gravity_well",
    "soul_furnace",
    "ancestral_molt",
    "dark_aegis",
    "mirror_theft",
    "prismatic_tempest",
    "inverse_law",
    "chronicle_repair",
    "causality_reversal",
}


def validate(catalog: dict) -> None:
    ids: set[str] = set()
    for dungeon in catalog["dungeons"]:
        assert len(dungeon["monsters"]) == 8, f"{dungeon['id']} must have 8 monsters"
        assert dungeon.get("pressure", {}).get("name"), f"{dungeon['id']} must have a pressure action name"
        assert dungeon["pressure"].get("type") in PRESSURE_TYPES, f"invalid pressure type: {dungeon['id']}"
        assert dungeon.get("mechanic") in MECHANICS, f"invalid dungeon mechanic: {dungeon['id']}"
        behavior_ids = set(dungeon.get("behaviors", {}))
        monster_ids = {monster["id"] for monster in dungeon["monsters"]}
        assert behavior_ids == monster_ids, f"behavior ids do not match monsters: {dungeon['id']}"
        assert all(behavior in BEHAVIORS for behavior in dungeon["behaviors"].values()), f"invalid behavior: {dungeon['id']}"
        boss_id = dungeon["monsters"][-1]["id"]
        assert dungeon["behaviors"][boss_id] == "boss", f"invalid boss behavior: {dungeon['id']}"
        assert all(dungeon["behaviors"][monster_id] != "boss" for monster_id in monster_ids - {boss_id}), f"invalid boss behavior: {dungeon['id']}"
        assert dungeon["id"] not in ids, f"duplicate id: {dungeon['id']}"
        ids.add(dungeon["id"])
        for monster in dungeon["monsters"]:
            assert monster["element"] in ELEMENT_LABELS, f"invalid element: {monster['element']}"
            assert monster["weakness"] in ELEMENT_LABELS, f"invalid weakness: {monster['weakness']}"
            assert monster["ailment"] in AILMENTS, f"invalid ailment: {monster['ailment']}"
            if unique_skill := monster.get("uniqueSkill"):
                assert unique_skill.get("name"), f"unique skill name is missing: {monster['id']}"
                assert unique_skill.get("description"), f"unique skill description is missing: {monster['id']}"
                assert unique_skill.get("type") in UNIQUE_SKILL_TYPES, f"invalid unique skill type: {monster['id']}"
                assert 0 < unique_skill.get("chance", 0) < 100, f"invalid unique skill chance: {monster['id']}"
            assert len(monster["materials"]) == 3, f"{monster['id']} must have 3 materials"
            generated_ids = [
                monster["id"],
                *(f"mat_{monster['id']}_{suffix}" for suffix, _ in monster["materials"]),
                *(f"{monster['id']}_{suffix}" for suffix in ("weapon", "armor", "shield", "accessory")),
            ]
            for item_id in generated_ids:
                assert item_id not in ids, f"duplicate id: {item_id}"
                ids.add(item_id)


def generate_content(catalog: dict) -> str:
    specs = json.dumps(catalog["dungeons"], ensure_ascii=False, indent=2)
    return f"""// This file is generated by scripts/generate-advanced-dungeons.py.
// Edit advanced-dungeon-catalog.json, then rerun the generator.

const ADVANCED_DUNGEON_SPECS = {specs};

const MAGIC_ELEMENTS = new Set(['water', 'ice', 'thunder', 'light', 'dark']);
const ELEMENT_NAMES = {{ fire: '炎', water: '水', grass: '草', ice: '氷', thunder: '雷', wind: '風', earth: '土', light: '光', dark: '闇' }};
const AILMENT_NAMES = {{ poison: '毒', burn: '火傷', paralysis: '麻痺', sleep: '睡眠', confusion: '混乱', curse: '呪い', blind: '暗闇', silence: '沈黙' }};

function livingParty(battle) {{
  return Array.isArray(battle.party) ? battle.party.filter(target => !target.isDead) : [];
}}

function livingEnemies(battle, attacker) {{
  const enemies = Array.isArray(battle.enemies) ? battle.enemies.filter(target => !target.isDead) : [];
  return enemies.length > 0 ? enemies : [attacker];
}}

function clearPositiveBuffs(target) {{
  for (const stat of ['atk', 'matk', 'def', 'mdef']) {{
    const turnsKey = `_${{stat}}BuffTurns`;
    const percentKey = `_${{stat}}BuffPercent`;
    const amountKey = `_${{stat}}BuffAmount`;
    if ((target[percentKey] || 0) > 0) target[percentKey] = 0;
    if ((target[amountKey] || 0) > 0) target[amountKey] = 0;
    if ((target[percentKey] || 0) === 0 && (target[amountKey] || 0) === 0) target[turnsKey] = 0;
  }}
  target._provokeTurns = 0;
  target._provokeChance = 0;
  target._ailmentResistBuffTurns = 0;
  target._ailmentResistBuffAmount = 0;
}}

function clearNegativeBuffs(target) {{
  for (const stat of ['atk', 'matk', 'def', 'mdef']) {{
    const turnsKey = `_${{stat}}BuffTurns`;
    const percentKey = `_${{stat}}BuffPercent`;
    const amountKey = `_${{stat}}BuffAmount`;
    if ((target[percentKey] || 0) < 0) target[percentKey] = 0;
    if ((target[amountKey] || 0) < 0) target[amountKey] = 0;
    if ((target[percentKey] || 0) === 0 && (target[amountKey] || 0) === 0) target[turnsKey] = 0;
  }}
}}

function applyOffenseBuff(target, percent, turns = 3) {{
  target._atkBuffPercent = Math.max(target._atkBuffPercent || 0, percent);
  target._atkBuffTurns = Math.max(target._atkBuffTurns || 0, turns);
  target._matkBuffPercent = Math.max(target._matkBuffPercent || 0, percent);
  target._matkBuffTurns = Math.max(target._matkBuffTurns || 0, turns);
}}

function applyOffenseBreak(target, percent, turns = 3) {{
  target._atkBuffPercent = Math.min(target._atkBuffPercent || 0, -percent);
  target._atkBuffTurns = Math.max(target._atkBuffTurns || 0, turns);
  target._matkBuffPercent = Math.min(target._matkBuffPercent || 0, -percent);
  target._matkBuffTurns = Math.max(target._matkBuffTurns || 0, turns);
}}

function applyDefenseBreak(target, percent, turns = 3) {{
  target._defBuffPercent = Math.min(target._defBuffPercent || 0, -percent);
  target._defBuffTurns = Math.max(target._defBuffTurns || 0, turns);
  target._mdefBuffPercent = Math.min(target._mdefBuffPercent || 0, -percent);
  target._mdefBuffTurns = Math.max(target._mdefBuffTurns || 0, turns);
}}

function currentHp(target) {{
  return target?.hp ? target.hp.current : target?.currentHp;
}}

const MECHANIC_DESCRIPTIONS = {{
  astral_fate: '星命効果で、命中した対象のATBを追加で奪う。',
  infernal_fury: '獄炎効果で、自身のHPが減るほど威力が上昇する。',
  dragon_blood: '竜血効果で、使用するたび自身の攻撃・魔攻が上昇する。',
  demon_siege: '魔城効果で、命中した対象の攻撃・魔攻を低下させる。',
  lunar_mirror: '月鏡効果で、命中した対象の強化効果を解除する。',
  storm_momentum: '風雷効果で対象のATBを奪い、自身の攻撃・魔攻を上げる。',
  labyrinth_dread: '迷界効果で対象のATBと攻撃・魔攻を大きく奪う。',
  time_erosion: '時蝕効果で、命中した対象のATBを0にする。',
  subspace_distortion: '亜空効果で、命中した対象の強化を消し、防御・魔防を低下させる。',
}};

function advancedActionDescription(monster, dungeon, dungeonIndex, behavior) {{
  const element = ELEMENT_NAMES[monster.element];
  const ailment = AILMENT_NAMES[monster.ailment];
  const severity = dungeonIndex >= 6 ? '高確率' : '確率';
  const atbDrain = 220 + dungeonIndex * 45;
  const hits = 2 + Math.floor(dungeonIndex / 4);
  const defenseBreak = 15 + dungeonIndex * 3;
  const drainPercent = 25 + dungeonIndex * 5;
  const targetScope = dungeonIndex >= 6 ? '生存者全員' : dungeonIndex >= 3 ? '最大3人' : '最大2人';
  const behaviorDescription = {{
    empower: `${{element}}属性の強襲。${{ailment}}を与え、自身の攻撃・魔攻を強化する。`,
    atb_drain: `${{element}}属性攻撃。${{severity}}で${{ailment}}を与え、対象のATBを${{atbDrain}}減少させる。`,
    sweep: `${{element}}属性で${{targetScope}}を攻撃し、${{ailment}}を与える。`,
    multi_hit: `${{element}}属性の${{hits}}連撃。各攻撃で${{ailment}}を与えることがある。`,
    dispel_break: `${{element}}属性攻撃。対象の強化効果を解除し、防御・魔防を${{defenseBreak}}%低下させる。`,
    drain: `${{element}}属性攻撃。${{ailment}}を与え、与えたダメージの${{drainPercent}}%だけHPを回復する。`,
    execute: `${{element}}属性の処刑攻撃。対象のHPが40%以下なら威力が1.65倍になる。`,
    commander: `${{element}}属性の全体攻撃。${{ailment}}を与え、生存中の敵全体の攻撃・魔攻を強化する。`,
    boss: `${{element}}属性の全体攻撃。${{severity}}で${{ailment}}を与え、全員のATBを${{atbDrain}}減少、防御・魔防を${{defenseBreak}}%低下させる。`,
  }}[behavior];
  return `${{behaviorDescription}} ${{MECHANIC_DESCRIPTIONS[dungeon.mechanic]}}`;
}}

function createAdvancedAction(monster, dungeon, dungeonIndex, floorIndex, isBoss) {{
  const behavior = dungeon.behaviors[monster.id];
  const multiplier = 10 + dungeonIndex * 0.9 + floorIndex * 0.25 + (isBoss ? 2 : 0);
  const ailmentChance = Math.min(90, 40 + dungeonIndex * 5 + (isBoss ? 10 : 0));
  const chance = isBoss ? 44 + dungeonIndex : 34 + dungeonIndex * 2;
  const isMagic = MAGIC_ELEMENTS.has(monster.element);
  return {{
    name: monster.action,
    chance,
    type: isMagic ? 'magic' : 'physical',
    isMagic,
    description: advancedActionDescription(monster, dungeon, dungeonIndex, behavior),
    execute: (attacker, defender, battle) => {{
      const originalElements = attacker.stats.attackElements;
      const originalAilments = attacker.stats.attackAilments;
      attacker.stats.attackElements = {{ [monster.element]: 100 }};
      attacker.stats.attackAilments = {{ ...(originalAilments || {{}}), [monster.ailment]: ailmentChance }};

      const party = livingParty(battle);
      const affectedTargets = new Set();
      const missingHpRatio = Math.max(0, 1 - attacker.currentHp / attacker.stats.hp);
      const furyMultiplier = dungeon.mechanic === 'infernal_fury' ? 1 + missingHpRatio * 0.4 : 1;
      const attack = (target, attackMultiplier = multiplier, hideActionName = false) => {{
        if (!target || target.isDead) return;
        affectedTargets.add(target);
        battle.executeAttack(attacker, target, false, {{
          actionName: monster.action,
          damageMultiplier: attackMultiplier * furyMultiplier,
          isMagic,
          damageType: 'skill',
          hideActionName,
        }});
      }};

      if (behavior === 'boss') {{
        party.forEach((target, index) => attack(target, multiplier, index > 0));
        party.forEach(target => {{
          target.atb = Math.max(0, (target.atb || 0) - (220 + dungeonIndex * 45));
          applyDefenseBreak(target, 15 + dungeonIndex * 3);
        }});
      }} else if (behavior === 'empower') {{
        attack(defender);
        applyOffenseBuff(attacker, 18 + dungeonIndex * 4);
        battle.showDamage?.(attacker.elementId, 'ATK/MATK UP', 'text-red-300');
      }} else if (behavior === 'atb_drain') {{
        attack(defender);
        defender.atb = Math.max(0, (defender.atb || 0) - (220 + dungeonIndex * 45));
        battle.showDamage?.(defender.elementId, 'ATB DOWN', 'text-yellow-400');
      }} else if (behavior === 'sweep') {{
        const targetCount = dungeonIndex >= 6 ? party.length : dungeonIndex >= 3 ? 3 : 2;
        const targets = [defender, ...party.filter(target => target !== defender)].slice(0, targetCount);
        targets.forEach((target, index) => attack(target, multiplier * 0.82, index > 0));
      }} else if (behavior === 'multi_hit') {{
        const hits = 2 + Math.floor(dungeonIndex / 4);
        for (let hit = 0; hit < hits && !defender.isDead; hit += 1) {{
          attack(defender, multiplier * 0.68, hit > 0);
        }}
      }} else if (behavior === 'dispel_break') {{
        attack(defender);
        if (!defender.isDead) {{
          clearPositiveBuffs(defender);
          applyDefenseBreak(defender, 15 + dungeonIndex * 3);
          battle.showDamage?.(defender.elementId, 'BUFF BREAK', 'text-blue-400');
        }}
      }} else if (behavior === 'drain') {{
        const hpBefore = currentHp(defender);
        attack(defender);
        const dealt = Math.max(0, (hpBefore || 0) - (currentHp(defender) || 0));
        const heal = Math.floor(dealt * (0.25 + dungeonIndex * 0.05));
        if (heal > 0) {{
          attacker.currentHp = Math.min(attacker.stats.hp, attacker.currentHp + heal);
          battle.showDamage?.(attacker.elementId, `+${{heal}}`, 'text-green-400');
        }}
      }} else if (behavior === 'execute') {{
        const maxHp = defender.stats?.hp || defender.hp?.max || defender.maxHp || currentHp(defender);
        const executeMultiplier = currentHp(defender) <= maxHp * 0.4 ? 1.65 : 1;
        attack(defender, multiplier * executeMultiplier);
      }} else if (behavior === 'commander') {{
        party.forEach((target, index) => attack(target, multiplier * 0.78, index > 0));
        livingEnemies(battle, attacker).forEach(target => applyOffenseBuff(target, 22 + dungeonIndex * 4));
        battle.showDamage?.(attacker.elementId, 'ENEMY ATK/MATK UP', 'text-red-300');
      }}

      if (dungeon.mechanic === 'astral_fate') {{
        affectedTargets.forEach(target => {{ target.atb = Math.max(0, (target.atb || 0) - 150); }});
      }} else if (dungeon.mechanic === 'dragon_blood') {{
        applyOffenseBuff(attacker, 24 + dungeonIndex * 3);
      }} else if (dungeon.mechanic === 'demon_siege') {{
        affectedTargets.forEach(target => applyOffenseBreak(target, 18));
      }} else if (dungeon.mechanic === 'lunar_mirror') {{
        affectedTargets.forEach(target => clearPositiveBuffs(target));
      }} else if (dungeon.mechanic === 'storm_momentum') {{
        affectedTargets.forEach(target => {{ target.atb = Math.max(0, (target.atb || 0) - 180); }});
        applyOffenseBuff(attacker, 20);
      }} else if (dungeon.mechanic === 'labyrinth_dread') {{
        affectedTargets.forEach(target => {{ target.atb = Math.max(0, (target.atb || 0) - 350); applyOffenseBreak(target, 15); }});
      }} else if (dungeon.mechanic === 'time_erosion') {{
        affectedTargets.forEach(target => {{ target.atb = 0; }});
      }} else if (dungeon.mechanic === 'subspace_distortion') {{
        affectedTargets.forEach(target => {{ clearPositiveBuffs(target); applyDefenseBreak(target, 25); }});
      }}

      attacker.stats.attackElements = originalElements;
      attacker.stats.attackAilments = originalAilments;
    }},
  }};
}}

function createUniqueAction(monster, dungeonIndex) {{
  const skill = monster.uniqueSkill;
  const attack = (attacker, target, battle, element, multiplier, ailments = {{}}) => {{
    if (!target || target.isDead) return;
    const originalElements = attacker.stats.attackElements;
    const originalAilments = attacker.stats.attackAilments;
    attacker.stats.attackElements = {{ [element]: 100 }};
    attacker.stats.attackAilments = {{ ...(originalAilments || {{}}), ...ailments }};
    battle.executeAttack(attacker, target, false, {{
      actionName: skill.name,
      damageMultiplier: multiplier,
      isMagic: MAGIC_ELEMENTS.has(element),
      damageType: 'skill',
      hideActionName: true,
    }});
    attacker.stats.attackElements = originalElements;
    attacker.stats.attackAilments = originalAilments;
  }};

  return {{
    name: skill.name,
    chance: skill.chance,
    type: ['ancestral_molt', 'dark_aegis', 'chronicle_repair'].includes(skill.type) ? 'support' : 'magic',
    isMagic: !['ancestral_molt', 'dark_aegis', 'chronicle_repair'].includes(skill.type),
    description: skill.description,
    execute: (attacker, defender, battle) => {{
      const party = livingParty(battle);
      const enemies = livingEnemies(battle, attacker);
      battle.showActionName?.(attacker.elementId, skill.name, 'text-cyan-200', 'border-cyan-400/60');

      if (skill.type === 'gravity_well') {{
        party.forEach(target => {{
          attack(attacker, target, battle, 'thunder', 7.4 + dungeonIndex * 0.4, {{ paralysis: 55 }});
          target.atb = Math.floor(Math.max(0, target.atb || 0) * 0.5);
        }});
      }} else if (skill.type === 'soul_furnace') {{
        const sacrifice = Math.floor(attacker.stats.hp * 0.06);
        attacker.currentHp = Math.max(1, attacker.currentHp - sacrifice);
        battle.showDamage?.(attacker.elementId, sacrifice, 'text-red-500');
        party.forEach(target => attack(attacker, target, battle, 'fire', 8 + dungeonIndex * 0.45, {{ burn: 60, curse: 45 }}));
      }} else if (skill.type === 'ancestral_molt') {{
        const heal = Math.floor(attacker.stats.hp * 0.12);
        attacker.currentHp = Math.min(attacker.stats.hp, attacker.currentHp + heal);
        attacker.activeAilment = null;
        clearNegativeBuffs(attacker);
        applyOffenseBuff(attacker, 35);
        battle.showDamage?.(attacker.elementId, `+${{heal}}`, 'text-green-400');
      }} else if (skill.type === 'dark_aegis') {{
        enemies.forEach(target => {{
          const barrier = Math.floor((target.stats?.hp || target.maxHp || currentHp(target) || 1) * 0.08);
          target._barrierHp = Math.max(target._barrierHp || 0, barrier);
          applyOffenseBuff(target, 25);
          battle.showDamage?.(target.elementId, `BARRIER +${{barrier}}`, 'text-blue-300');
        }});
      }} else if (skill.type === 'mirror_theft') {{
        const stolen = Object.fromEntries(['atk', 'matk', 'def', 'mdef'].map(stat => [stat, {{
          percent: Math.max(0, defender[`_${{stat}}BuffPercent`] || 0),
          amount: Math.max(0, defender[`_${{stat}}BuffAmount`] || 0),
        }}]));
        clearPositiveBuffs(defender);
        for (const [stat, buff] of Object.entries(stolen)) {{
          if (buff.percent <= 0 && buff.amount <= 0) continue;
          attacker[`_${{stat}}BuffPercent`] = Math.max(attacker[`_${{stat}}BuffPercent`] || 0, buff.percent);
          attacker[`_${{stat}}BuffAmount`] = Math.max(attacker[`_${{stat}}BuffAmount`] || 0, buff.amount);
          attacker[`_${{stat}}BuffTurns`] = Math.max(attacker[`_${{stat}}BuffTurns`] || 0, 3);
        }}
        attack(attacker, defender, battle, 'light', 10 + dungeonIndex * 0.5, {{ confusion: 55 }});
      }} else if (skill.type === 'prismatic_tempest') {{
        const multiplier = 3.1 + dungeonIndex * 0.18;
        for (const element of ['wind', 'thunder', 'light']) {{
          party.forEach(target => attack(attacker, target, battle, element, multiplier, element === 'light' ? {{ confusion: 60 }} : {{}}));
        }}
      }} else if (skill.type === 'inverse_law') {{
        party.forEach(target => {{
          attack(attacker, target, battle, 'light', 6.2 + dungeonIndex * 0.35, {{ confusion: 70 }});
          target.atb = Math.max(0, 1000 - Math.min(1000, target.atb || 0));
        }});
      }} else if (skill.type === 'chronicle_repair') {{
        enemies.forEach(target => {{
          const maxHp = target.stats?.hp || target.maxHp || currentHp(target) || 1;
          const heal = Math.floor(maxHp * 0.08);
          target.currentHp = Math.min(maxHp, currentHp(target) + heal);
          target.activeAilment = null;
          clearNegativeBuffs(target);
          target.atb = Math.min(1000, (target.atb || 0) + 250);
          battle.showDamage?.(target.elementId, `+${{heal}}`, 'text-green-400');
        }});
      }} else if (skill.type === 'causality_reversal') {{
        const positiveBuffs = Object.fromEntries(['atk', 'matk', 'def', 'mdef'].map(stat => [stat, {{
          percent: Math.max(0, defender[`_${{stat}}BuffPercent`] || 0),
          amount: Math.max(0, defender[`_${{stat}}BuffAmount`] || 0),
        }}]));
        attack(attacker, defender, battle, 'light', 12 + dungeonIndex * 0.55, {{ confusion: 75 }});
        if (!defender.isDead) {{
          clearPositiveBuffs(defender);
          for (const [stat, buff] of Object.entries(positiveBuffs)) {{
            if (buff.percent <= 0 && buff.amount <= 0) continue;
            if (buff.percent > 0) defender[`_${{stat}}BuffPercent`] = -Math.max(20, buff.percent);
            if (buff.amount > 0) defender[`_${{stat}}BuffAmount`] = -buff.amount;
            defender[`_${{stat}}BuffTurns`] = Math.max(defender[`_${{stat}}BuffTurns`] || 0, 3);
          }}
        }}
      }}
    }},
  }};
}}

const PRESSURE_DESCRIPTIONS = {{
  astral_acceleration: '星の加護で敵全体の攻撃・魔攻を強化し、自身のHPを5%回復する。',
  infernal_rebirth: '業火で自身のHPを8%回復し、攻撃・魔攻を大幅に強化する。',
  dragon_dominion: '竜威で敵全体を強化し、味方全員の防御・魔防を15%低下させる。',
  demon_command: '魔王の号令で敵全体を強化し、味方全員のATBを250減少させる。',
  lunar_eclipse: '月蝕で味方全員の強化効果を解除し、ATBを300減少させる。',
  storm_rule: '天候を支配して敵全体の魔攻を強化し、味方全員のATBと魔防を奪う。',
  labyrinth_inversion: '迷宮法則を反転し、味方全員の強化を解除してATBと防御・魔防を大きく奪う。',
  time_stop: '時間を停止して味方全員のATBを0にし、防御・魔防を30%低下させる。',
  law_collapse: '世界法則を崩壊させ、味方全員の強化とATBを消去。敵全体を凶暴化し、自身を回復する。',
}};

function createPressureAction(dungeon, dungeonIndex) {{
  const pressure = dungeon.pressure;
  return {{
    name: pressure.name,
    chance: 18 + Math.floor(dungeonIndex / 2),
    type: 'support',
    isMagic: false,
    description: PRESSURE_DESCRIPTIONS[pressure.type],
    execute: (attacker, defender, battle) => {{
      const party = livingParty(battle);
      const enemies = livingEnemies(battle, attacker);
      const heal = rate => {{
        const amount = Math.floor(attacker.stats.hp * rate);
        attacker.currentHp = Math.min(attacker.stats.hp, attacker.currentHp + amount);
        battle.showDamage?.(attacker.elementId, `+${{amount}}`, 'text-green-400');
      }};
      battle.showActionName?.(attacker.elementId, pressure.name, 'text-fuchsia-300', 'border-fuchsia-500/50');

      if (pressure.type === 'astral_acceleration') {{
        enemies.forEach(target => applyOffenseBuff(target, 30));
        heal(0.05);
      }} else if (pressure.type === 'infernal_rebirth') {{
        applyOffenseBuff(attacker, 40);
        heal(0.08);
      }} else if (pressure.type === 'dragon_dominion') {{
        enemies.forEach(target => applyOffenseBuff(target, 35));
        party.forEach(target => applyDefenseBreak(target, 15));
      }} else if (pressure.type === 'demon_command') {{
        enemies.forEach(target => applyOffenseBuff(target, 45));
        party.forEach(target => {{ target.atb = Math.max(0, (target.atb || 0) - 250); }});
      }} else if (pressure.type === 'lunar_eclipse') {{
        party.forEach(target => {{ clearPositiveBuffs(target); target.atb = Math.max(0, (target.atb || 0) - 300); }});
      }} else if (pressure.type === 'storm_rule') {{
        enemies.forEach(target => applyOffenseBuff(target, 45));
        party.forEach(target => {{ target.atb = Math.max(0, (target.atb || 0) - 350); applyDefenseBreak(target, 25); }});
      }} else if (pressure.type === 'labyrinth_inversion') {{
        party.forEach(target => {{ clearPositiveBuffs(target); target.atb = Math.max(0, (target.atb || 0) - 500); applyDefenseBreak(target, 25); }});
      }} else if (pressure.type === 'time_stop') {{
        party.forEach(target => {{ target.atb = 0; applyDefenseBreak(target, 30); }});
        heal(0.06);
      }} else if (pressure.type === 'law_collapse') {{
        party.forEach(target => {{ clearPositiveBuffs(target); target.atb = 0; applyDefenseBreak(target, 35); }});
        enemies.forEach(target => applyOffenseBuff(target, 60));
        heal(0.1);
      }}
    }},
  }};
}}

function materialId(monster, material) {{
  return `mat_${{monster.id}}_${{material[0]}}`;
}}

function roundStat(value) {{
  return Math.round(value / 10) * 10;
}}

const ENTRIES = ADVANCED_DUNGEON_SPECS.flatMap((dungeon, dungeonIndex) =>
  dungeon.monsters.map((monster, floorIndex) => ({{
    dungeon,
    dungeonIndex,
    monster,
    floorIndex,
    tier: dungeonIndex * 8 + floorIndex,
    isBoss: floorIndex === dungeon.monsters.length - 1,
  }}))
);

export const ADVANCED_DUNGEONS = ADVANCED_DUNGEON_SPECS.map(dungeon => ({{
  id: dungeon.id,
  name: dungeon.name,
  description: dungeon.description,
  bgImage: dungeon.bgImage,
  theme: dungeon.theme,
  isUnlocked: false,
  floors: dungeon.monsters.map((monster, index) => ({{
    level: index + 1,
    monsters: index === 0 || index === dungeon.monsters.length - 1
      ? [{{ [monster.id]: 1, weight: 100 }}]
      : [
          {{ [monster.id]: 1, weight: 65 }},
          {{ [dungeon.monsters[index - 1].id]: 1, [monster.id]: 1, weight: 35 }},
        ],
  }})),
}}));

export const ADVANCED_MONSTERS = ENTRIES.map(({{ dungeon, dungeonIndex, monster, floorIndex, tier, isBoss }}) => {{
  const growth = 1.025 ** tier;
  const bossGrowth = isBoss ? 1.8 : 1;
  return {{
    id: monster.id,
    name: monster.name,
    stats: {{
      hp: roundStat(3300000 * growth * bossGrowth),
      atk: roundStat(38000 * (1.023 ** tier) * (isBoss ? 1.3 : 1)),
      def: roundStat(32000 * (1.022 ** tier) * (isBoss ? 1.25 : 1)),
      matk: roundStat(36000 * (1.023 ** tier) * (isBoss ? 1.3 : 1)),
      mdef: roundStat(33000 * (1.022 ** tier) * (isBoss ? 1.25 : 1)),
      spd: 650 + tier * 11 + (isBoss ? 80 : 0),
    }},
    elements: {{ [monster.element]: 150, [monster.weakness]: -200 }},
    ailments: {{ [monster.ailment]: isBoss ? 70 : 45 }},
    rewards: {{
      exp: 3200 + tier * 140 + (isBoss ? 1800 : 0),
      jp: 850 + tier * 35 + (isBoss ? 450 : 0),
      gold: 1600 + tier * 80 + (isBoss ? 1000 : 0),
    }},
    drops: monster.materials.map((material, index) => ({{
      itemId: materialId(monster, material),
      rate: [5, 1, 0.1][index],
    }})),
    actions: [
      createAdvancedAction(monster, dungeon, dungeonIndex, floorIndex, isBoss),
      ...(monster.uniqueSkill ? [createUniqueAction(monster, dungeonIndex)] : []),
      ...(isBoss ? [createPressureAction(dungeon, dungeonIndex)] : []),
    ],
  }};
}});

export const ADVANCED_MATERIALS = ENTRIES.flatMap(({{ monster }}) =>
  monster.materials.map(material => ({{ id: materialId(monster, material), name: material[1] }}))
);

function equipmentBase(entry) {{
  const {{ dungeonIndex, monster, tier, isBoss }} = entry;
  const power = 540 + tier * 12 + (isBoss ? 25 : 0);
  const elementPower = Math.min(45, 25 + Math.floor(dungeonIndex / 2) * 5);
  const materialIds = monster.materials.map(material => materialId(monster, material));
  const price = 320000 + tier * 10000 + (isBoss ? 50000 : 0);
  return {{ power, elementPower, materialIds, price }};
}}

function recipe(price, materialIds, firstIndex, secondIndex) {{
  return {{
    price,
    materials: [
      {{ id: materialIds[firstIndex], amount: 40 }},
      {{ id: materialIds[secondIndex], amount: 10 }},
    ],
  }};
}}

export const ADVANCED_WEAPONS = ENTRIES.map(entry => {{
  const {{ monster }} = entry;
  const {{ power, elementPower, materialIds, price }} = equipmentBase(entry);
  return {{
    id: `${{monster.id}}_weapon`,
    name: monster.weapon,
    stats: {{ atk: power, matk: roundStat(power * 0.7), spd: roundStat(power * 0.48) }},
    elements: {{ [monster.element]: elementPower }},
    recipe: recipe(price, materialIds, 0, 1),
  }};
}});

export const ADVANCED_ARMORS = ENTRIES.map(entry => {{
  const {{ monster }} = entry;
  const {{ power, elementPower, materialIds, price }} = equipmentBase(entry);
  return {{
    id: `${{monster.id}}_armor`,
    name: `${{monster.gearTheme}}の戦装`,
    stats: {{ def: power, mdef: roundStat(power * 0.7) }},
    elements: {{ [monster.element]: elementPower }},
    recipe: recipe(price, materialIds, 1, 2),
  }};
}});

export const ADVANCED_SHIELDS = ENTRIES.map(entry => {{
  const {{ monster }} = entry;
  const {{ power, elementPower, materialIds, price }} = equipmentBase(entry);
  return {{
    id: `${{monster.id}}_shield`,
    name: `${{monster.gearTheme}}の護盾`,
    stats: {{ def: power, hp: roundStat(power * 0.55) }},
    elements: {{ [monster.element]: elementPower }},
    recipe: recipe(price, materialIds, 0, 2),
  }};
}});

export const ADVANCED_ACCESSORIES = ENTRIES.map(entry => {{
  const {{ monster }} = entry;
  const {{ power, elementPower, materialIds, price }} = equipmentBase(entry);
  return {{
    id: `${{monster.id}}_accessory`,
    name: `${{monster.gearTheme}}の秘宝`,
    stats: {{ matk: power, spd: roundStat(power * 0.5) }},
    elements: {{ [monster.element]: elementPower }},
    recipe: recipe(price, materialIds, 1, 2),
  }};
}});
"""


def md_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def table(headers: list[str], rows: list[list[str]]) -> list[str]:
    result = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    result.extend("| " + " | ".join(md_escape(str(cell)) for cell in row) + " |" for row in rows)
    return result


def generate_doc(catalog: dict) -> str:
    dungeons = catalog["dungeons"]
    monster_count = sum(len(d["monsters"]) for d in dungeons)
    material_count = monster_count * 3
    equipment_count = monster_count * 4
    lines = [
        "# 追加ダンジョン画像仕様一覧",
        "",
        "> この文書は `js/definitions/advanced-dungeon-catalog.json` から自動生成しています。ID・名称を変更した場合は `python3 scripts/generate-advanced-dungeons.py` を実行してください。",
        "",
        "## 共通仕様",
        "",
        "- 対象: 今回実装した9ダンジョンのモンスター・素材・武器・防具・盾・アクセサリ。",
        "- 推奨形式: WebP、正方形、背景透過。元データは512×512px以上、ゲーム配置用は128×128px程度を想定。",
        "- 画風: 既存アセットに合わせた高密度な後期16bit〜初期32bit風JRPGピクセルアート。輪郭と材質が小サイズでも判別できること。",
        "- 禁止: 文字、数字、ロゴ、透かし、額縁、UI、複数アイテムを並べた構図。画像は対象1点を中央配置すること。",
        "- 保存先は各表の `パス` を使用すること。ファイル名はIDと完全一致させること。",
        "",
        "## 件数",
        "",
        *table(["カテゴリ", "枚数"], [
            ["モンスター", str(monster_count)],
            ["素材", str(material_count)],
            ["武器", str(monster_count)],
            ["防具", str(monster_count)],
            ["盾", str(monster_count)],
            ["アクセサリ", str(monster_count)],
            ["合計", str(monster_count + material_count + equipment_count)],
        ]),
    ]
    for dungeon in dungeons:
        lines.extend(["", f"## {dungeon['name']} (`{dungeon['id']}`)", "", "### モンスター", ""])
        monster_rows = []
        material_rows = []
        equipment_rows = {"武器": [], "防具": [], "盾": [], "アクセサリ": []}
        for monster in dungeon["monsters"]:
            element = ELEMENT_LABELS[monster["element"]]
            monster_rows.append([
                f"`{monster['id']}`",
                monster["name"],
                f"`assets/monster/{monster['id']}.webp`",
                monster["concept"],
            ])
            material_ids = []
            for suffix, name in monster["materials"]:
                item_id = f"mat_{monster['id']}_{suffix}"
                material_ids.append(item_id)
                material_rows.append([
                    f"`{item_id}`",
                    name,
                    f"`assets/material/{item_id}.webp`",
                    f"{monster['name']}由来の「{name}」を単体で描く。名称から分かる身体部位・魔力・遺物の材質を強調した素材アイコン。",
                ])
            equipment = [
                ("武器", f"{monster['id']}_weapon", monster["weapon"], "assets/weapon", "武器全体の形状が読める斜め向きの装備アイコン"),
                ("防具", f"{monster['id']}_armor", f"{monster['gearTheme']}の戦装", "assets/armor", "胴装備を正面寄りに見せた装備アイコン"),
                ("盾", f"{monster['id']}_shield", f"{monster['gearTheme']}の護盾", "assets/shield", "盾面の意匠が読める正面寄りの装備アイコン"),
                ("アクセサリ", f"{monster['id']}_accessory", f"{monster['gearTheme']}の秘宝", "assets/accessory", "宝飾と魔力核が判別できる単体アクセサリアイコン"),
            ]
            for category, item_id, name, directory, framing in equipment:
                equipment_rows[category].append([
                    f"`{item_id}`",
                    name,
                    f"`{directory}/{item_id}.webp`",
                    f"{monster['name']}の意匠と{element}属性の色・発光を取り入れた{framing}。",
                ])
        lines.extend(table(["ID", "名称", "パス", "用意すべき画像"], monster_rows))
        lines.extend(["", "### 素材", ""])
        lines.extend(table(["ID", "名称", "パス", "用意すべき画像"], material_rows))
        for category in ("武器", "防具", "盾", "アクセサリ"):
            lines.extend(["", f"### {category}", ""])
            lines.extend(table(["ID", "名称", "パス", "用意すべき画像"], equipment_rows[category]))
    lines.extend(["", "## 実装済み背景", ""])
    lines.extend(table(["ダンジョンID", "背景パス"], [[f"`{d['id']}`", f"`{d['bgImage']}`"] for d in dungeons]))
    lines.append("")
    return "\n".join(lines)


def image_entries(catalog: dict) -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    equipment_entries: dict[str, list[dict[str, str]]] = {
        "weapon": [],
        "armor": [],
        "shield": [],
        "accessory": [],
    }
    for dungeon in catalog["dungeons"]:
        for monster in dungeon["monsters"]:
            element = ELEMENT_LABELS[monster["element"]]
            entries.append({
                "category": "monster",
                "id": monster["id"],
                "name": monster["name"],
                "path": f"assets/monster/{monster['id']}.webp",
                "visual": f"{monster['concept']} 全身が画面内に収まる単体モンスター。",
            })
    for dungeon in catalog["dungeons"]:
        for monster in dungeon["monsters"]:
            for suffix, name in monster["materials"]:
                item_id = f"mat_{monster['id']}_{suffix}"
                entries.append({
                    "category": "material",
                    "id": item_id,
                    "name": name,
                    "path": f"assets/material/{item_id}.webp",
                    "visual": f"{monster['name']}由来の「{name}」。名称から判別できる身体部位・魔力・遺物の材質を強調した単体素材。",
                })
            equipment = [
                ("weapon", f"{monster['id']}_weapon", monster["weapon"], "assets/weapon", "武器全体の形状が明瞭に読める斜め向き"),
                ("armor", f"{monster['id']}_armor", f"{monster['gearTheme']}の戦装", "assets/armor", "胴装備の形状と材質が読める正面寄り"),
                ("shield", f"{monster['id']}_shield", f"{monster['gearTheme']}の護盾", "assets/shield", "盾面の意匠が明瞭に読める正面寄り"),
                ("accessory", f"{monster['id']}_accessory", f"{monster['gearTheme']}の秘宝", "assets/accessory", "宝飾と魔力核が判別できる正面寄り"),
            ]
            for category, item_id, name, directory, framing in equipment:
                equipment_entries[category].append({
                    "category": category,
                    "id": item_id,
                    "name": name,
                    "path": f"{directory}/{item_id}.webp",
                    "visual": f"{monster['name']}の意匠と{element}属性の色・発光を取り入れた「{name}」。{framing}の単体装備。",
                })
    for category in ("weapon", "armor", "shield", "accessory"):
        entries.extend(equipment_entries[category])
    return entries


CATEGORY_LABELS = {
    "monster": "MONSTER",
    "material": "MATERIAL",
    "weapon": "WEAPON",
    "armor": "ARMOR",
    "shield": "SHIELD",
    "accessory": "ACCESSORY",
}

CATEGORY_SLUGS = {
    "monster": "monster",
    "material": "material",
    "weapon": "weapon",
    "armor": "armor",
    "shield": "shield",
    "accessory": "accessory",
}


def prompt_filename(batch_number: int, batch: list[dict[str, str]]) -> str:
    categories = list(dict.fromkeys(entry["category"] for entry in batch))
    slug = "-".join(CATEGORY_SLUGS[category] for category in categories)
    return f"5x5_{batch_number:03d}_{slug}.md"


def generate_grid_prompt(batch_number: int, batch: list[dict[str, str]], total_batches: int) -> str:
    lines = [
        f"# JRPG Ultra-Detailed High-Density Pixel Art Icon Grid — Batch {batch_number:03d}/{total_batches:03d}",
        "",
        "Please generate a single, high-resolution image perfectly formatted as a structured **5x5 grid** of individual, highly detailed pixel art assets. This image is for a professional game asset pack and MUST adhere to the following strict requirements.",
        "",
        "## CORE ABSOLUTE REQUIREMENTS",
        "",
        "- **Format:** A single image containing the entire 5x5 grid. Exactly 5 columns and exactly 5 rows.",
        "- **Order:** Follow the numbered cell list in strict row-major order, from top-left to bottom-right. Do not reorder, merge, omit, or replace subjects.",
        "- **Aspect Ratio:** The entire image must be perfectly square. Use equal square cells; 128x128 or 256x256 pixels per cell is recommended.",
        "- **Text:** **ABSOLUTELY NO TEXT, NO LETTERS, NO NUMBERS, NO CHARACTERS, NO LABELS, NO WATERMARKS, NO TITLES** anywhere inside the generated image. The IDs and names below are instructions only and must never be rendered.",
        "- **One Subject Per Cell:** Each non-empty cell contains exactly one requested monster or item. No extra props, duplicate subjects, scenery, hands, stands, frames, or UI.",
        "- **Structure:**",
        "    - Each asset must stay fully inside its own square cell with generous padding and no overlap into adjacent cells.",
        "    - Use one perfectly flat, uniform neutral medium-gray background in every cell (#808080 suggested), with no texture, gradient, floor plane, reflection, or cast shadow.",
        "    - Separate all cells with a clean, straight 1px black border to form an exact 5x5 grid. Do not add an ornamental outer frame.",
        "    - Keep visual scale consistent within each category. Preserve a complete, readable silhouette at crop size.",
        "- **Style:**",
        "    - **Refined late 16-bit to early 32-bit console RPG pixel art style** (high-quality SNES/PS1 hybrid).",
        "    - **Ultra-detailed, high-resolution pixel art** with high pixel density and crisp intentional pixel clusters.",
        "    - Sophisticated pixel shading, controlled anti-aliasing, clear highlights and shadows, and strong small-size readability.",
        "    - Materials must be recognizable: faceted crystal, worked metal, patina, bone, scale, fur, cloth folds, magical cores, and gems as appropriate.",
        "    - Monster cells: one full-body creature in a readable three-quarter pose, fully inside the cell, no environment or ground shadow.",
        "    - Item cells: one centered inventory icon at a readable three-quarter or front angle as specified, with no wielder or mannequin.",
        "",
        "## Grid Contents",
        "",
        "Fill cells in the exact order below. `ASSET_ID` and `SAVE_PATH` are production metadata only—never draw them in the image.",
        "",
    ]
    for cell in range(25):
        row = cell // 5 + 1
        column = cell % 5 + 1
        if cell < len(batch):
            entry = batch[cell]
            lines.append(
                f"{cell + 1}. **Row {row}, Column {column}** — "
                f"CATEGORY: {CATEGORY_LABELS[entry['category']]} | "
                f"ASSET_ID: `{entry['id']}` | NAME: {entry['name']} | "
                f"SAVE_PATH: `{entry['path']}` | VISUAL: {entry['visual']}"
            )
        else:
            lines.append(
                f"{cell + 1}. **Row {row}, Column {column}** — EMPTY CELL. Render only the same perfectly flat #808080 background; no subject, symbol, decoration, shadow, or mark."
            )
    lines.extend([
        "",
        "## FINAL VALIDATION BEFORE OUTPUT",
        "",
        "- The canvas is square and visibly divided into exactly 25 equal cells.",
        "- Every requested subject appears once in its assigned cell and nowhere else.",
        "- Empty cells, if any, contain only flat gray.",
        "- No text-like marks, letters, numbers, labels, signatures, logos, or watermarks are visible.",
        "- Nothing crosses a cell border, and every subject can be cropped cleanly into an independent square image.",
        "",
    ])
    lines.extend(f"- {entry['id']}" for entry in batch)
    lines.append("")
    return "\n".join(lines)


def generate_prompt_files(catalog: dict) -> tuple[list[Path], str]:
    entries = image_entries(catalog)
    batches: list[list[dict[str, str]]] = []
    for category in ("monster", "material", "weapon", "armor", "shield", "accessory"):
        category_entries = [entry for entry in entries if entry["category"] == category]
        batches.extend(category_entries[index:index + 25] for index in range(0, len(category_entries), 25))
    PROMPT_DIR.mkdir(parents=True, exist_ok=True)
    for stale_path in PROMPT_DIR.glob("5x5_*.md"):
        stale_path.unlink()
    paths: list[Path] = []
    index_rows: list[list[str]] = []
    for batch_number, batch in enumerate(batches, start=1):
        filename = prompt_filename(batch_number, batch)
        path = PROMPT_DIR / filename
        path.write_text(generate_grid_prompt(batch_number, batch, len(batches)), encoding="utf-8")
        paths.append(path)
        categories = " / ".join(dict.fromkeys(CATEGORY_LABELS[entry["category"]] for entry in batch))
        index_rows.append([
            f"[{filename}]({filename})",
            str(len(batch)),
            categories,
            f"`{batch[0]['id']}`",
            f"`{batch[-1]['id']}`",
            str(25 - len(batch)),
        ])
    index_lines = [
        "# 追加ダンジョン 5x5画像生成プロンプト一覧",
        "",
        "各Markdownファイルを1ファイルずつ外部画像生成AIへ渡してください。生成画像は上段左から右へ、行単位で1〜25番の順です。",
        "",
        f"- 対象画像: {len(entries)}件",
        f"- プロンプト: {len(paths)}ファイル",
        f"- 25件入りバッチ: {sum(len(batch) == 25 for batch in batches)}ファイル",
        f"- カテゴリ末尾の部分バッチ: {sum(len(batch) < 25 for batch in batches)}ファイル",
        f"- 全部分バッチの空マス合計: {sum(25 - len(batch) for batch in batches)}個",
        "- モンスター・素材・各装備カテゴリは、生成品質を安定させるため同じグリッド内で混在させていません。",
        "",
        *table(["プロンプト", "画像数", "カテゴリ", "先頭ID", "末尾ID", "空マス"], index_rows),
        "",
        "## 切り出し時の注意",
        "",
        "- 生成画像を5等分×5等分し、各ファイル内の `SAVE_PATH` に対応させてください。",
        "- IDや名称は生成画像内に描画させず、切り出したファイル名としてのみ使用してください。",
        "- 各カテゴリ末尾バッチの空マスは破棄してください。",
        "",
    ]
    index_text = "\n".join(index_lines)
    (PROMPT_DIR / "README.md").write_text(index_text, encoding="utf-8")
    return paths, index_text


def validate_prompt_files(catalog: dict, paths: list[Path]) -> None:
    expected_entries = image_entries(catalog)
    expected_ids = [entry["id"] for entry in expected_entries]
    expected_metadata = [(entry["id"], entry["path"]) for entry in expected_entries]
    assert len(expected_ids) == 576
    assert len(set(expected_ids)) == len(expected_ids)
    assert len(paths) == math.ceil(len(expected_ids) / 25)
    actual_ids: list[str] = []
    actual_metadata: list[tuple[str, str]] = []
    total_slots = 0
    for path in paths:
        text = path.read_text(encoding="utf-8")
        numbered_cells = re.findall(r"(?m)^(\d+)\. \*\*Row (\d), Column (\d)\*\*", text)
        expected_cells = [(str(index), str((index - 1) // 5 + 1), str((index - 1) % 5 + 1)) for index in range(1, 26)]
        assert numbered_cells == expected_cells, f"{path.name}: grid positions are invalid"
        categories = set(re.findall(r"CATEGORY: ([A-Z]+)", text))
        assert len(categories) == 1, f"{path.name}: categories are mixed"
        metadata = re.findall(r"ASSET_ID: `([^`]+)` .*? SAVE_PATH: `([^`]+)`", text)
        terminal_ids = re.findall(r"(?m)^- ([a-z0-9_]+)$", text)
        assert terminal_ids == [item_id for item_id, _ in metadata], f"{path.name}: terminal ID list is invalid"
        actual_ids.extend(item_id for item_id, _ in metadata)
        actual_metadata.extend(metadata)
        total_slots += len(numbered_cells)
    assert actual_ids == expected_ids, "prompt asset order differs from catalog"
    assert actual_metadata == expected_metadata, "prompt save paths differ from catalog"
    assert total_slots - len(actual_ids) == 24, "unexpected empty-cell count"


def main() -> None:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    validate(catalog)
    CONTENT_PATH.write_text(generate_content(catalog), encoding="utf-8")
    DOC_PATH.write_text(generate_doc(catalog), encoding="utf-8")
    prompt_paths, _ = generate_prompt_files(catalog)
    validate_prompt_files(catalog, prompt_paths)
    print(f"generated {CONTENT_PATH.relative_to(ROOT)}")
    print(f"generated {DOC_PATH.relative_to(ROOT)}")
    print(f"generated {len(prompt_paths)} prompt files in {PROMPT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
