#!/usr/bin/env python3
"""Generate advanced dungeon definitions and their image specification document."""

from __future__ import annotations

import json
import math
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "js/definitions/advanced-dungeon-catalog.json"
CONTENT_PATH = ROOT / "js/definitions/advanced-dungeon-content.js"
DOC_PATH = ROOT / "Doc/追加ダンジョン画像仕様一覧.md"
PROMPT_DIR = ROOT / "Doc/追加ダンジョン5x5画像生成プロンプト"

ELEMENT_LABELS = {
    "fire": "炎",
    "water": "水",
    "grass": "草",
    "ice": "氷",
    "thunder": "雷",
    "wind": "風",
    "earth": "土",
    "light": "光",
    "dark": "闇",
}
AILMENTS = {"poison", "burn", "paralysis", "sleep", "confusion", "curse", "blind", "silence"}


def validate(catalog: dict) -> None:
    ids: set[str] = set()
    for dungeon in catalog["dungeons"]:
        assert len(dungeon["monsters"]) == 8, f"{dungeon['id']} must have 8 monsters"
        assert dungeon["id"] not in ids, f"duplicate id: {dungeon['id']}"
        ids.add(dungeon["id"])
        for monster in dungeon["monsters"]:
            assert monster["element"] in ELEMENT_LABELS, f"invalid element: {monster['element']}"
            assert monster["weakness"] in ELEMENT_LABELS, f"invalid weakness: {monster['weakness']}"
            assert monster["ailment"] in AILMENTS, f"invalid ailment: {monster['ailment']}"
            assert len(monster["materials"]) == 3, f"{monster['id']} must have 3 materials"
            generated_ids = [
                monster["id"],
                *(f"mat_{monster['id']}_{suffix}" for suffix, _ in monster["materials"]),
                *(f"{monster['id']}_{suffix}" for suffix in ("weapon", "armor", "shield", "accessory")),
            ]
            for item_id in generated_ids:
                assert item_id not in ids, f"duplicate id: {item_id}"
                ids.add(item_id)


def generate_content(catalog: dict) -> str:
    specs = json.dumps(catalog["dungeons"], ensure_ascii=False, indent=2)
    return f"""// This file is generated by scripts/generate-advanced-dungeons.py.
// Edit advanced-dungeon-catalog.json, then rerun the generator.

const ADVANCED_DUNGEON_SPECS = {specs};

const MAGIC_ELEMENTS = new Set(['water', 'ice', 'thunder', 'light', 'dark']);
const ELEMENT_NAMES = {{ fire: '炎', water: '水', grass: '草', ice: '氷', thunder: '雷', wind: '風', earth: '土', light: '光', dark: '闇' }};
const AILMENT_NAMES = {{ poison: '毒', burn: '火傷', paralysis: '麻痺', sleep: '睡眠', confusion: '混乱', curse: '呪い', blind: '暗闇', silence: '沈黙' }};

function createAdvancedAction(monster, tier, isBoss) {{
  const multiplier = 10 + Math.floor(tier / 8) * 0.8 + (isBoss ? 2 : 0);
  return {{
    name: monster.action,
    chance: isBoss ? 45 : 35,
    description: `${{ELEMENT_NAMES[monster.element]}}属性の${{isBoss ? '全体' : '強力な'}}固有攻撃。${{AILMENT_NAMES[monster.ailment]}}を付与することがある。`,
    execute: (attacker, defender, battle) => {{
      const originalElements = attacker.stats.attackElements;
      const originalAilments = attacker.stats.attackAilments;
      attacker.stats.attackElements = {{ [monster.element]: 100 }};
      attacker.stats.attackAilments = {{ ...(originalAilments || {{}}), [monster.ailment]: isBoss ? 65 : 45 }};
      const targets = isBoss && Array.isArray(battle.party)
        ? battle.party.filter(target => !target.isDead)
        : [defender];
      targets.forEach((target, index) => battle.executeAttack(attacker, target, false, {{
        actionName: monster.action,
        damageMultiplier: multiplier,
        isMagic: MAGIC_ELEMENTS.has(monster.element),
        damageType: 'skill',
        hideActionName: index > 0,
      }}));
      attacker.stats.attackElements = originalElements;
      attacker.stats.attackAilments = originalAilments;
    }},
  }};
}}

function materialId(monster, material) {{
  return `mat_${{monster.id}}_${{material[0]}}`;
}}

function roundStat(value) {{
  return Math.round(value / 10) * 10;
}}

const ENTRIES = ADVANCED_DUNGEON_SPECS.flatMap((dungeon, dungeonIndex) =>
  dungeon.monsters.map((monster, floorIndex) => ({{
    dungeon,
    dungeonIndex,
    monster,
    floorIndex,
    tier: dungeonIndex * 8 + floorIndex,
    isBoss: floorIndex === dungeon.monsters.length - 1,
  }}))
);

export const ADVANCED_DUNGEONS = ADVANCED_DUNGEON_SPECS.map(dungeon => ({{
  id: dungeon.id,
  name: dungeon.name,
  description: dungeon.description,
  bgImage: dungeon.bgImage,
  theme: dungeon.theme,
  isUnlocked: false,
  floors: dungeon.monsters.map((monster, index) => ({{
    level: index + 1,
    monsters: index === 0 || index === dungeon.monsters.length - 1
      ? [{{ [monster.id]: 1, weight: 100 }}]
      : [
          {{ [monster.id]: 1, weight: 65 }},
          {{ [dungeon.monsters[index - 1].id]: 1, [monster.id]: 1, weight: 35 }},
        ],
  }})),
}}));

export const ADVANCED_MONSTERS = ENTRIES.map(({{ monster, tier, isBoss }}) => {{
  const growth = 1.025 ** tier;
  const bossGrowth = isBoss ? 1.8 : 1;
  return {{
    id: monster.id,
    name: monster.name,
    stats: {{
      hp: roundStat(3300000 * growth * bossGrowth),
      atk: roundStat(38000 * (1.023 ** tier) * (isBoss ? 1.3 : 1)),
      def: roundStat(32000 * (1.022 ** tier) * (isBoss ? 1.25 : 1)),
      matk: roundStat(36000 * (1.023 ** tier) * (isBoss ? 1.3 : 1)),
      mdef: roundStat(33000 * (1.022 ** tier) * (isBoss ? 1.25 : 1)),
      spd: 650 + tier * 11 + (isBoss ? 80 : 0),
    }},
    elements: {{ [monster.element]: 150, [monster.weakness]: -200 }},
    ailments: {{ [monster.ailment]: isBoss ? 70 : 45 }},
    rewards: {{
      exp: 3200 + tier * 140 + (isBoss ? 1800 : 0),
      jp: 850 + tier * 35 + (isBoss ? 450 : 0),
      gold: 1600 + tier * 80 + (isBoss ? 1000 : 0),
    }},
    drops: monster.materials.map((material, index) => ({{
      itemId: materialId(monster, material),
      rate: [5, 1, 0.1][index],
    }})),
    actions: [createAdvancedAction(monster, tier, isBoss)],
  }};
}});

export const ADVANCED_MATERIALS = ENTRIES.flatMap(({{ monster }}) =>
  monster.materials.map(material => ({{ id: materialId(monster, material), name: material[1] }}))
);

function equipmentBase(entry) {{
  const {{ dungeonIndex, monster, tier, isBoss }} = entry;
  const power = 540 + tier * 12 + (isBoss ? 25 : 0);
  const elementPower = Math.min(45, 25 + Math.floor(dungeonIndex / 2) * 5);
  const materialIds = monster.materials.map(material => materialId(monster, material));
  const price = 320000 + tier * 10000 + (isBoss ? 50000 : 0);
  return {{ power, elementPower, materialIds, price }};
}}

function recipe(price, materialIds, firstIndex, secondIndex) {{
  return {{
    price,
    materials: [
      {{ id: materialIds[firstIndex], amount: 40 }},
      {{ id: materialIds[secondIndex], amount: 10 }},
    ],
  }};
}}

export const ADVANCED_WEAPONS = ENTRIES.map(entry => {{
  const {{ monster }} = entry;
  const {{ power, elementPower, materialIds, price }} = equipmentBase(entry);
  return {{
    id: `${{monster.id}}_weapon`,
    name: monster.weapon,
    stats: {{ atk: power, matk: roundStat(power * 0.7), spd: roundStat(power * 0.48) }},
    elements: {{ [monster.element]: elementPower }},
    recipe: recipe(price, materialIds, 0, 1),
  }};
}});

export const ADVANCED_ARMORS = ENTRIES.map(entry => {{
  const {{ monster }} = entry;
  const {{ power, elementPower, materialIds, price }} = equipmentBase(entry);
  return {{
    id: `${{monster.id}}_armor`,
    name: `${{monster.gearTheme}}の戦装`,
    stats: {{ def: power, mdef: roundStat(power * 0.7) }},
    elements: {{ [monster.element]: elementPower }},
    recipe: recipe(price, materialIds, 1, 2),
  }};
}});

export const ADVANCED_SHIELDS = ENTRIES.map(entry => {{
  const {{ monster }} = entry;
  const {{ power, elementPower, materialIds, price }} = equipmentBase(entry);
  return {{
    id: `${{monster.id}}_shield`,
    name: `${{monster.gearTheme}}の護盾`,
    stats: {{ def: power, hp: roundStat(power * 0.55) }},
    elements: {{ [monster.element]: elementPower }},
    recipe: recipe(price, materialIds, 0, 2),
  }};
}});

export const ADVANCED_ACCESSORIES = ENTRIES.map(entry => {{
  const {{ monster }} = entry;
  const {{ power, elementPower, materialIds, price }} = equipmentBase(entry);
  return {{
    id: `${{monster.id}}_accessory`,
    name: `${{monster.gearTheme}}の秘宝`,
    stats: {{ matk: power, spd: roundStat(power * 0.5) }},
    elements: {{ [monster.element]: elementPower }},
    recipe: recipe(price, materialIds, 1, 2),
  }};
}});
"""


def md_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def table(headers: list[str], rows: list[list[str]]) -> list[str]:
    result = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    result.extend("| " + " | ".join(md_escape(str(cell)) for cell in row) + " |" for row in rows)
    return result


def generate_doc(catalog: dict) -> str:
    dungeons = catalog["dungeons"]
    monster_count = sum(len(d["monsters"]) for d in dungeons)
    material_count = monster_count * 3
    equipment_count = monster_count * 4
    lines = [
        "# 追加ダンジョン画像仕様一覧",
        "",
        "> この文書は `js/definitions/advanced-dungeon-catalog.json` から自動生成しています。ID・名称を変更した場合は `python3 scripts/generate-advanced-dungeons.py` を実行してください。",
        "",
        "## 共通仕様",
        "",
        "- 対象: 今回実装した9ダンジョンのモンスター・素材・武器・防具・盾・アクセサリ。",
        "- 推奨形式: WebP、正方形、背景透過。元データは512×512px以上、ゲーム配置用は128×128px程度を想定。",
        "- 画風: 既存アセットに合わせた高密度な後期16bit〜初期32bit風JRPGピクセルアート。輪郭と材質が小サイズでも判別できること。",
        "- 禁止: 文字、数字、ロゴ、透かし、額縁、UI、複数アイテムを並べた構図。画像は対象1点を中央配置すること。",
        "- 保存先は各表の `パス` を使用すること。ファイル名はIDと完全一致させること。",
        "",
        "## 件数",
        "",
        *table(["カテゴリ", "枚数"], [
            ["モンスター", str(monster_count)],
            ["素材", str(material_count)],
            ["武器", str(monster_count)],
            ["防具", str(monster_count)],
            ["盾", str(monster_count)],
            ["アクセサリ", str(monster_count)],
            ["合計", str(monster_count + material_count + equipment_count)],
        ]),
    ]
    for dungeon in dungeons:
        lines.extend(["", f"## {dungeon['name']} (`{dungeon['id']}`)", "", "### モンスター", ""])
        monster_rows = []
        material_rows = []
        equipment_rows = {"武器": [], "防具": [], "盾": [], "アクセサリ": []}
        for monster in dungeon["monsters"]:
            element = ELEMENT_LABELS[monster["element"]]
            monster_rows.append([
                f"`{monster['id']}`",
                monster["name"],
                f"`assets/monster/{monster['id']}.webp`",
                monster["concept"],
            ])
            material_ids = []
            for suffix, name in monster["materials"]:
                item_id = f"mat_{monster['id']}_{suffix}"
                material_ids.append(item_id)
                material_rows.append([
                    f"`{item_id}`",
                    name,
                    f"`assets/material/{item_id}.webp`",
                    f"{monster['name']}由来の「{name}」を単体で描く。名称から分かる身体部位・魔力・遺物の材質を強調した素材アイコン。",
                ])
            equipment = [
                ("武器", f"{monster['id']}_weapon", monster["weapon"], "assets/weapon", "武器全体の形状が読める斜め向きの装備アイコン"),
                ("防具", f"{monster['id']}_armor", f"{monster['gearTheme']}の戦装", "assets/armor", "胴装備を正面寄りに見せた装備アイコン"),
                ("盾", f"{monster['id']}_shield", f"{monster['gearTheme']}の護盾", "assets/shield", "盾面の意匠が読める正面寄りの装備アイコン"),
                ("アクセサリ", f"{monster['id']}_accessory", f"{monster['gearTheme']}の秘宝", "assets/accessory", "宝飾と魔力核が判別できる単体アクセサリアイコン"),
            ]
            for category, item_id, name, directory, framing in equipment:
                equipment_rows[category].append([
                    f"`{item_id}`",
                    name,
                    f"`{directory}/{item_id}.webp`",
                    f"{monster['name']}の意匠と{element}属性の色・発光を取り入れた{framing}。",
                ])
        lines.extend(table(["ID", "名称", "パス", "用意すべき画像"], monster_rows))
        lines.extend(["", "### 素材", ""])
        lines.extend(table(["ID", "名称", "パス", "用意すべき画像"], material_rows))
        for category in ("武器", "防具", "盾", "アクセサリ"):
            lines.extend(["", f"### {category}", ""])
            lines.extend(table(["ID", "名称", "パス", "用意すべき画像"], equipment_rows[category]))
    lines.extend(["", "## 実装済み背景", ""])
    lines.extend(table(["ダンジョンID", "背景パス"], [[f"`{d['id']}`", f"`{d['bgImage']}`"] for d in dungeons]))
    lines.append("")
    return "\n".join(lines)


def image_entries(catalog: dict) -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    equipment_entries: dict[str, list[dict[str, str]]] = {
        "weapon": [],
        "armor": [],
        "shield": [],
        "accessory": [],
    }
    for dungeon in catalog["dungeons"]:
        for monster in dungeon["monsters"]:
            element = ELEMENT_LABELS[monster["element"]]
            entries.append({
                "category": "monster",
                "id": monster["id"],
                "name": monster["name"],
                "path": f"assets/monster/{monster['id']}.webp",
                "visual": f"{monster['concept']} 全身が画面内に収まる単体モンスター。",
            })
    for dungeon in catalog["dungeons"]:
        for monster in dungeon["monsters"]:
            for suffix, name in monster["materials"]:
                item_id = f"mat_{monster['id']}_{suffix}"
                entries.append({
                    "category": "material",
                    "id": item_id,
                    "name": name,
                    "path": f"assets/material/{item_id}.webp",
                    "visual": f"{monster['name']}由来の「{name}」。名称から判別できる身体部位・魔力・遺物の材質を強調した単体素材。",
                })
            equipment = [
                ("weapon", f"{monster['id']}_weapon", monster["weapon"], "assets/weapon", "武器全体の形状が明瞭に読める斜め向き"),
                ("armor", f"{monster['id']}_armor", f"{monster['gearTheme']}の戦装", "assets/armor", "胴装備の形状と材質が読める正面寄り"),
                ("shield", f"{monster['id']}_shield", f"{monster['gearTheme']}の護盾", "assets/shield", "盾面の意匠が明瞭に読める正面寄り"),
                ("accessory", f"{monster['id']}_accessory", f"{monster['gearTheme']}の秘宝", "assets/accessory", "宝飾と魔力核が判別できる正面寄り"),
            ]
            for category, item_id, name, directory, framing in equipment:
                equipment_entries[category].append({
                    "category": category,
                    "id": item_id,
                    "name": name,
                    "path": f"{directory}/{item_id}.webp",
                    "visual": f"{monster['name']}の意匠と{element}属性の色・発光を取り入れた「{name}」。{framing}の単体装備。",
                })
    for category in ("weapon", "armor", "shield", "accessory"):
        entries.extend(equipment_entries[category])
    return entries


CATEGORY_LABELS = {
    "monster": "MONSTER",
    "material": "MATERIAL",
    "weapon": "WEAPON",
    "armor": "ARMOR",
    "shield": "SHIELD",
    "accessory": "ACCESSORY",
}

CATEGORY_SLUGS = {
    "monster": "monster",
    "material": "material",
    "weapon": "weapon",
    "armor": "armor",
    "shield": "shield",
    "accessory": "accessory",
}


def prompt_filename(batch_number: int, batch: list[dict[str, str]]) -> str:
    categories = list(dict.fromkeys(entry["category"] for entry in batch))
    slug = "-".join(CATEGORY_SLUGS[category] for category in categories)
    return f"5x5_{batch_number:03d}_{slug}.md"


def generate_grid_prompt(batch_number: int, batch: list[dict[str, str]], total_batches: int) -> str:
    lines = [
        f"# JRPG Ultra-Detailed High-Density Pixel Art Icon Grid — Batch {batch_number:03d}/{total_batches:03d}",
        "",
        "Please generate a single, high-resolution image perfectly formatted as a structured **5x5 grid** of individual, highly detailed pixel art assets. This image is for a professional game asset pack and MUST adhere to the following strict requirements.",
        "",
        "## CORE ABSOLUTE REQUIREMENTS",
        "",
        "- **Format:** A single image containing the entire 5x5 grid. Exactly 5 columns and exactly 5 rows.",
        "- **Order:** Follow the numbered cell list in strict row-major order, from top-left to bottom-right. Do not reorder, merge, omit, or replace subjects.",
        "- **Aspect Ratio:** The entire image must be perfectly square. Use equal square cells; 128x128 or 256x256 pixels per cell is recommended.",
        "- **Text:** **ABSOLUTELY NO TEXT, NO LETTERS, NO NUMBERS, NO CHARACTERS, NO LABELS, NO WATERMARKS, NO TITLES** anywhere inside the generated image. The IDs and names below are instructions only and must never be rendered.",
        "- **One Subject Per Cell:** Each non-empty cell contains exactly one requested monster or item. No extra props, duplicate subjects, scenery, hands, stands, frames, or UI.",
        "- **Structure:**",
        "    - Each asset must stay fully inside its own square cell with generous padding and no overlap into adjacent cells.",
        "    - Use one perfectly flat, uniform neutral medium-gray background in every cell (#808080 suggested), with no texture, gradient, floor plane, reflection, or cast shadow.",
        "    - Separate all cells with a clean, straight 1px black border to form an exact 5x5 grid. Do not add an ornamental outer frame.",
        "    - Keep visual scale consistent within each category. Preserve a complete, readable silhouette at crop size.",
        "- **Style:**",
        "    - **Refined late 16-bit to early 32-bit console RPG pixel art style** (high-quality SNES/PS1 hybrid).",
        "    - **Ultra-detailed, high-resolution pixel art** with high pixel density and crisp intentional pixel clusters.",
        "    - Sophisticated pixel shading, controlled anti-aliasing, clear highlights and shadows, and strong small-size readability.",
        "    - Materials must be recognizable: faceted crystal, worked metal, patina, bone, scale, fur, cloth folds, magical cores, and gems as appropriate.",
        "    - Monster cells: one full-body creature in a readable three-quarter pose, fully inside the cell, no environment or ground shadow.",
        "    - Item cells: one centered inventory icon at a readable three-quarter or front angle as specified, with no wielder or mannequin.",
        "",
        "## Grid Contents",
        "",
        "Fill cells in the exact order below. `ASSET_ID` and `SAVE_PATH` are production metadata only—never draw them in the image.",
        "",
    ]
    for cell in range(25):
        row = cell // 5 + 1
        column = cell % 5 + 1
        if cell < len(batch):
            entry = batch[cell]
            lines.append(
                f"{cell + 1}. **Row {row}, Column {column}** — "
                f"CATEGORY: {CATEGORY_LABELS[entry['category']]} | "
                f"ASSET_ID: `{entry['id']}` | NAME: {entry['name']} | "
                f"SAVE_PATH: `{entry['path']}` | VISUAL: {entry['visual']}"
            )
        else:
            lines.append(
                f"{cell + 1}. **Row {row}, Column {column}** — EMPTY CELL. Render only the same perfectly flat #808080 background; no subject, symbol, decoration, shadow, or mark."
            )
    lines.extend([
        "",
        "## FINAL VALIDATION BEFORE OUTPUT",
        "",
        "- The canvas is square and visibly divided into exactly 25 equal cells.",
        "- Every requested subject appears once in its assigned cell and nowhere else.",
        "- Empty cells, if any, contain only flat gray.",
        "- No text-like marks, letters, numbers, labels, signatures, logos, or watermarks are visible.",
        "- Nothing crosses a cell border, and every subject can be cropped cleanly into an independent square image.",
        "",
    ])
    lines.extend(f"- {entry['id']}" for entry in batch)
    lines.append("")
    return "\n".join(lines)


def generate_prompt_files(catalog: dict) -> tuple[list[Path], str]:
    entries = image_entries(catalog)
    batches: list[list[dict[str, str]]] = []
    for category in ("monster", "material", "weapon", "armor", "shield", "accessory"):
        category_entries = [entry for entry in entries if entry["category"] == category]
        batches.extend(category_entries[index:index + 25] for index in range(0, len(category_entries), 25))
    PROMPT_DIR.mkdir(parents=True, exist_ok=True)
    for stale_path in PROMPT_DIR.glob("5x5_*.md"):
        stale_path.unlink()
    paths: list[Path] = []
    index_rows: list[list[str]] = []
    for batch_number, batch in enumerate(batches, start=1):
        filename = prompt_filename(batch_number, batch)
        path = PROMPT_DIR / filename
        path.write_text(generate_grid_prompt(batch_number, batch, len(batches)), encoding="utf-8")
        paths.append(path)
        categories = " / ".join(dict.fromkeys(CATEGORY_LABELS[entry["category"]] for entry in batch))
        index_rows.append([
            f"[{filename}]({filename})",
            str(len(batch)),
            categories,
            f"`{batch[0]['id']}`",
            f"`{batch[-1]['id']}`",
            str(25 - len(batch)),
        ])
    index_lines = [
        "# 追加ダンジョン 5x5画像生成プロンプト一覧",
        "",
        "各Markdownファイルを1ファイルずつ外部画像生成AIへ渡してください。生成画像は上段左から右へ、行単位で1〜25番の順です。",
        "",
        f"- 対象画像: {len(entries)}件",
        f"- プロンプト: {len(paths)}ファイル",
        f"- 25件入りバッチ: {sum(len(batch) == 25 for batch in batches)}ファイル",
        f"- カテゴリ末尾の部分バッチ: {sum(len(batch) < 25 for batch in batches)}ファイル",
        f"- 全部分バッチの空マス合計: {sum(25 - len(batch) for batch in batches)}個",
        "- モンスター・素材・各装備カテゴリは、生成品質を安定させるため同じグリッド内で混在させていません。",
        "",
        *table(["プロンプト", "画像数", "カテゴリ", "先頭ID", "末尾ID", "空マス"], index_rows),
        "",
        "## 切り出し時の注意",
        "",
        "- 生成画像を5等分×5等分し、各ファイル内の `SAVE_PATH` に対応させてください。",
        "- IDや名称は生成画像内に描画させず、切り出したファイル名としてのみ使用してください。",
        "- 各カテゴリ末尾バッチの空マスは破棄してください。",
        "",
    ]
    index_text = "\n".join(index_lines)
    (PROMPT_DIR / "README.md").write_text(index_text, encoding="utf-8")
    return paths, index_text


def validate_prompt_files(catalog: dict, paths: list[Path]) -> None:
    expected_entries = image_entries(catalog)
    expected_ids = [entry["id"] for entry in expected_entries]
    expected_metadata = [(entry["id"], entry["path"]) for entry in expected_entries]
    assert len(expected_ids) == 576
    assert len(set(expected_ids)) == len(expected_ids)
    assert len(paths) == math.ceil(len(expected_ids) / 25)
    actual_ids: list[str] = []
    actual_metadata: list[tuple[str, str]] = []
    total_slots = 0
    for path in paths:
        text = path.read_text(encoding="utf-8")
        numbered_cells = re.findall(r"(?m)^(\d+)\. \*\*Row (\d), Column (\d)\*\*", text)
        expected_cells = [(str(index), str((index - 1) // 5 + 1), str((index - 1) % 5 + 1)) for index in range(1, 26)]
        assert numbered_cells == expected_cells, f"{path.name}: grid positions are invalid"
        categories = set(re.findall(r"CATEGORY: ([A-Z]+)", text))
        assert len(categories) == 1, f"{path.name}: categories are mixed"
        metadata = re.findall(r"ASSET_ID: `([^`]+)` .*? SAVE_PATH: `([^`]+)`", text)
        terminal_ids = re.findall(r"(?m)^- ([a-z0-9_]+)$", text)
        assert terminal_ids == [item_id for item_id, _ in metadata], f"{path.name}: terminal ID list is invalid"
        actual_ids.extend(item_id for item_id, _ in metadata)
        actual_metadata.extend(metadata)
        total_slots += len(numbered_cells)
    assert actual_ids == expected_ids, "prompt asset order differs from catalog"
    assert actual_metadata == expected_metadata, "prompt save paths differ from catalog"
    assert total_slots - len(actual_ids) == 24, "unexpected empty-cell count"


def main() -> None:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    validate(catalog)
    CONTENT_PATH.write_text(generate_content(catalog), encoding="utf-8")
    DOC_PATH.write_text(generate_doc(catalog), encoding="utf-8")
    prompt_paths, _ = generate_prompt_files(catalog)
    validate_prompt_files(catalog, prompt_paths)
    print(f"generated {CONTENT_PATH.relative_to(ROOT)}")
    print(f"generated {DOC_PATH.relative_to(ROOT)}")
    print(f"generated {len(prompt_paths)} prompt files in {PROMPT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
