/**
 * このファイルは素材やドロップアイテムなど、装備できないアイテムのデータをまとめたファイルです。
 * 
 * 素材・消費アイテムなどのデータ定義ファイル
 * 
 * 装備できないアイテム（モンスターのドロップ品など）を定義します。
 */

export const MATERIALS = [
  { id: 'slime_blue_jelly'      , name: 'ブルースライムのゼリー'          , sellPrice: 1 },
  { id: 'slime_blue_core'       , name: 'ブルースライムのコア'            , sellPrice: 2 },
  { id: 'slime_blue_fluid'      , name: 'ブルースライムの体液'            , sellPrice: 3 },
  { id: 'slime_green_jelly'     , name: 'グリーンスライムのゼリー'        , sellPrice: 1 },
  { id: 'slime_green_core'      , name: 'グリーンスライムのコア'          , sellPrice: 2 },
  { id: 'slime_green_fluid'     , name: 'グリーンスライムの体液'          , sellPrice: 3 },
  { id: 'slime_red_jelly'       , name: 'レッドスライムのゼリー'          , sellPrice: 1 },
  { id: 'slime_red_core'        , name: 'レッドスライムのコア'            , sellPrice: 2 },
  { id: 'slime_red_fluid'       , name: 'レッドスライムの体液'            , sellPrice: 3 },
  { id: 'slime_water_jelly'     , name: 'ウォータースライムのゼリー'      , sellPrice: 1 },
  { id: 'slime_water_core'      , name: 'ウォータースライムのコア'        , sellPrice: 2 },
  { id: 'slime_water_fluid'     , name: 'ウォータースライムの体液'        , sellPrice: 3 },
  { id: 'slime_fire_jelly'      , name: 'ファイヤースライムのゼリー'      , sellPrice: 1 },
  { id: 'slime_fire_core'       , name: 'ファイヤースライムのコア'        , sellPrice: 2 },
  { id: 'slime_fire_fluid'      , name: 'ファイヤースライムの体液'        , sellPrice: 3 },
  { id: 'slime_ice_jelly'       , name: 'アイススライムのゼリー'          , sellPrice: 1 },
  { id: 'slime_ice_core'        , name: 'アイススライムのコア'            , sellPrice: 2 },
  { id: 'slime_ice_fluid'       , name: 'アイススライムの体液'            , sellPrice: 3 },
  { id: 'slime_wind_jelly'      , name: 'ウインドスライムのゼリー'        , sellPrice: 1 },
  { id: 'slime_wind_core'       , name: 'ウインドスライムのコア'          , sellPrice: 2 },
  { id: 'slime_wind_fluid'      , name: 'ウインドスライムの体液'          , sellPrice: 3 },
  { id: 'slime_thunder_jelly'   , name: 'サンダースライムのゼリー'        , sellPrice: 1 },
  { id: 'slime_thunder_core'    , name: 'サンダースライムのコア'          , sellPrice: 2 },
  { id: 'slime_thunder_fluid'   , name: 'サンダースライムの体液'          , sellPrice: 3 },
  { id: 'slime_flower_jelly'    , name: 'フラワースライムのゼリー'        , sellPrice: 1 },
  { id: 'slime_flower_core'     , name: 'フラワースライムのコア'          , sellPrice: 2 },
  { id: 'slime_flower_fluid'    , name: 'フラワースライムの体液'          , sellPrice: 3 },
  { id: 'slime_grass_jelly'     , name: 'グラススライムのゼリー'          , sellPrice: 1 },
  { id: 'slime_grass_core'      , name: 'グラススライムのコア'            , sellPrice: 2 },
  { id: 'slime_grass_fluid'     , name: 'グラススライムの体液'            , sellPrice: 3 },
  { id: 'slime_dark_jelly'      , name: 'ダークスライムのゼリー'          , sellPrice: 1 },
  { id: 'slime_dark_core'       , name: 'ダークスライムのコア'            , sellPrice: 2 },
  { id: 'slime_dark_fluid'      , name: 'ダークスライムの体液'            , sellPrice: 3 },
  { id: 'slime_earth_jelly'     , name: 'アーススライムのゼリー'          , sellPrice: 1 },
  { id: 'slime_earth_core'      , name: 'アーススライムのコア'            , sellPrice: 2 },
  { id: 'slime_earth_fluid'     , name: 'アーススライムの体液'            , sellPrice: 3 },
  { id: 'slime_angel_jelly'     , name: 'エンジェルスライムのゼリー'      , sellPrice: 1 },
  { id: 'slime_angel_core'      , name: 'エンジェルスライムのコア'        , sellPrice: 2 },
  { id: 'slime_angel_fluid'     , name: 'エンジェルスライムの体液'        , sellPrice: 3 },
  { id: 'slime_king_jelly'      , name: 'キングスライムのゼリー'          , sellPrice: 1 },
  { id: 'slime_king_core'       , name: 'キングスライムのコア'            , sellPrice: 2 },
  { id: 'slime_king_fluid'      , name: 'キングスライムの体液'            , sellPrice: 3 },
  { id: 'slime_angel_king_jelly', name: 'エンジェルキングスライムのゼリー', sellPrice: 1 },
  { id: 'slime_angel_king_core' , name: 'エンジェルキングスライムのコア'  , sellPrice: 2 },
  { id: 'slime_angel_king_fluid', name: 'エンジェルキングスライムの体液'  , sellPrice: 3 },

    { id: 'spider_cave_silk'      , name: 'ケイブスパイダーの糸'            , sellPrice: 4 },
    { id: 'spider_cave_fang'      , name: 'ケイブスパイダーの牙'            , sellPrice: 5 },
    { id: 'spider_cave_venom'     , name: 'ケイブスパイダーの毒液'          , sellPrice: 6 },
    { id: 'spider_poison_silk'    , name: 'ポイズンスパイダーの糸'          , sellPrice: 4 },
    { id: 'spider_poison_fang'    , name: 'ポイズンスパイダーの牙'          , sellPrice: 5 },
    { id: 'spider_poison_venom'   , name: 'ポイズンスパイダーの毒液'        , sellPrice: 6 },
    { id: 'spider_trapdoor_silk'  , name: 'トラップドアスパイダーの糸'      , sellPrice: 4 },
    { id: 'spider_trapdoor_fang'  , name: 'トラップドアスパイダーの牙'      , sellPrice: 5 },
    { id: 'spider_trapdoor_venom' , name: 'トラップドアスパイダーの毒液'    , sellPrice: 6 },
    { id: 'weaver_web_silk'       , name: 'ウェブウィーバーの糸'            , sellPrice: 4 },
    { id: 'weaver_web_fang'       , name: 'ウェブウィーバーの牙'            , sellPrice: 5 },
    { id: 'weaver_web_venom'      , name: 'ウェブウィーバーの毒液'          , sellPrice: 6 },
    { id: 'spitter_acid_silk'     , name: 'アシッドスピッターの糸'          , sellPrice: 4 },
    { id: 'spitter_acid_fang'     , name: 'アシッドスピッターの牙'          , sellPrice: 5 },
    { id: 'spitter_acid_venom'    , name: 'アシッドスピッターの毒液'        , sellPrice: 6 },
    { id: 'arachnid_shadow_silk'  , name: 'シャドウアラクニドの糸'          , sellPrice: 4 },
    { id: 'arachnid_shadow_fang'  , name: 'シャドウアラクニドの牙'          , sellPrice: 5 },
    { id: 'arachnid_shadow_venom' , name: 'シャドウアラクニドの毒液'        , sellPrice: 6 },
    { id: 'tick_blood_silk'       , name: 'ブラッドティックの糸'            , sellPrice: 4 },
    { id: 'tick_blood_fang'       , name: 'ブラッドティックの牙'            , sellPrice: 5 },
    { id: 'tick_blood_venom'      , name: 'ブラッドティックの毒液'          , sellPrice: 6 },
    { id: 'crawler_bone_silk'     , name: 'ボーンクロウラーの糸'            , sellPrice: 4 },
    { id: 'crawler_bone_fang'     , name: 'ボーンクロウラーの牙'            , sellPrice: 5 },
    { id: 'crawler_bone_venom'    , name: 'ボーンクロウラーの毒液'          , sellPrice: 6 },
    { id: 'swarm_spider_silk'     , name: 'スパイダースウォームの糸'        , sellPrice: 4 },
    { id: 'swarm_spider_fang'     , name: 'スパイダースウォームの牙'        , sellPrice: 5 },
    { id: 'swarm_spider_venom'    , name: 'スパイダースウォームの毒液'      , sellPrice: 6 },
    { id: 'spider_dark_silk'      , name: 'ダークウィドウの糸'              , sellPrice: 4 },
    { id: 'spider_dark_fang'      , name: 'ダークウィドウの牙'              , sellPrice: 5 },
    { id: 'spider_dark_venom'     , name: 'ダークウィドウの毒液'            , sellPrice: 6 },
    { id: 'weaver_golden_silk'    , name: 'ゴールデンウィーバーの糸'        , sellPrice: 4 },
    { id: 'weaver_golden_fang'    , name: 'ゴールデンウィーバーの牙'        , sellPrice: 5 },
    { id: 'weaver_golden_venom'   , name: 'ゴールデンウィーバーの毒液'      , sellPrice: 6 },
    { id: 'arachnid_crystal_silk' , name: 'クリスタルアラクニドの糸'        , sellPrice: 4 },
    { id: 'arachnid_crystal_fang' , name: 'クリスタルアラクニドの牙'        , sellPrice: 5 },
    { id: 'arachnid_crystal_venom', name: 'クリスタルアラクニドの毒液'      , sellPrice: 6 },
    { id: 'boss_broodmother_silk' , name: 'ブルードマザーの糸'              , sellPrice: 4 },
    { id: 'boss_broodmother_fang' , name: 'ブルードマザーの牙'              , sellPrice: 5 },
    { id: 'boss_broodmother_venom', name: 'ブルードマザーの毒液'            , sellPrice: 6 },
    { id: 'boss_arachne_silk'     , name: 'アラクネ・クイーンの糸'          , sellPrice: 4 },
    { id: 'boss_arachne_fang'     , name: 'アラクネ・クイーンの牙'          , sellPrice: 5 },
    { id: 'boss_arachne_venom'    , name: 'アラクネ・クイーンの毒液'        , sellPrice: 6 },
    { id: 'boss_deathweaver_silk' , name: 'デスウィーバーの糸'              , sellPrice: 4 },
    { id: 'boss_deathweaver_fang' , name: 'デスウィーバーの牙'              , sellPrice: 5 },
    { id: 'boss_deathweaver_venom', name: 'デスウィーバーの毒液'            , sellPrice: 6 },
    { id: 'mat_crisp_shard', name: 'クリスプの欠片', sellPrice: 8 },
    { id: 'mat_crisp_core', name: 'クリスプの核', sellPrice: 15 },
    { id: 'mat_crisp_resonance_crystal', name: '共鳴する水明石', sellPrice: 50 },
    { id: 'mat_geode_shell', name: 'ジオードの甲羅', sellPrice: 8 },
    { id: 'mat_geode_amethyst', name: '紫水晶の原石', sellPrice: 15 },
    { id: 'mat_geode_heart', name: 'ジオードの心臓', sellPrice: 50 },
    { id: 'mat_snow_crystal', name: '雪花の結晶', sellPrice: 8 },
    { id: 'mat_snow_frog_dust', name: '氷精の粉', sellPrice: 15 },
    { id: 'mat_snow_frog_spirit', name: '絶対零度の核', sellPrice: 50 },
    { id: 'mat_crystalinos_horn', name: 'クリスタライノスの角', sellPrice: 8 },
    { id: 'mat_crystalinos_armor', name: '砕けない水晶装甲', sellPrice: 15 },
    { id: 'mat_crystalinos_soul', name: '巨獣の結晶魂', sellPrice: 50 },
    { id: 'mat_garnet_fang', name: '柘榴石の牙', sellPrice: 8 },
    { id: 'mat_garnet_pelt', name: '紅玉狼の毛皮', sellPrice: 15 },
    { id: 'mat_garnet_eye', name: 'ガーネットの血瞳', sellPrice: 50 },
    { id: 'mat_amber_scale', name: '琥珀の鱗', sellPrice: 8 },
    { id: 'mat_amber_venom', name: '太古の猛毒液', sellPrice: 15 },
    { id: 'mat_amber_fossil', name: '完全な琥珀化石', sellPrice: 50 },
    { id: 'mat_beryl_stone', name: '緑柱石の塊', sellPrice: 8 },
    { id: 'mat_beryl_core', name: '遺跡守護者の動力核', sellPrice: 15 },
    { id: 'mat_beryl_reactor', name: 'ベリルリアクター', sellPrice: 50 },
    { id: 'mat_jewel_wing', name: '宝石の翅', sellPrice: 8 },
    { id: 'mat_jewel_blade', name: '金剛石の鎌刃', sellPrice: 15 },
    { id: 'mat_jewel_diamond', name: '完全無欠のダイヤ', sellPrice: 50 },
    { id: 'mat_fluorite_powder', name: '蛍石の鱗粉', sellPrice: 8 },
    { id: 'mat_fluorite_wing', name: '幻惑の蝶翅', sellPrice: 15 },
    { id: 'mat_fluorite_illusion', name: '無限の幻夢結晶', sellPrice: 50 },
    { id: 'mat_pyrite_scale', name: '黄鉄鉱の鱗', sellPrice: 8 },
    { id: 'mat_pyrite_fang', name: '愚者の毒牙', sellPrice: 15 },
    { id: 'mat_pyrite_fool_gold', name: '真なる愚者の黄金', sellPrice: 50 },
    { id: 'mat_luminous_leaf', name: '光樹の葉', sellPrice: 10 },
    { id: 'mat_luminous_sap', name: '光満ちる樹液', sellPrice: 20 },
    { id: 'mat_luminous_flower', name: 'ジギタリスの極光花', sellPrice: 100 },
    { id: 'mat_opal_dust', name: 'オパールの砂', sellPrice: 10 },
    { id: 'mat_opal_fragment', name: '遊色の欠片', sellPrice: 20 },
    { id: 'mat_opal_chaos', name: '混沌のオパール核', sellPrice: 100 },
    { id: 'mat_diamond_scale', name: '金剛竜の鱗', sellPrice: 12 },
    { id: 'mat_diamond_claw', name: '金剛竜の光爪', sellPrice: 25 },
    { id: 'mat_diamond_laser_core', name: '極大光線の竜核', sellPrice: 150 },
    { id: 'mat_regalia_shard', name: '王権の破片', sellPrice: 12 },
    { id: 'mat_regalia_crown', name: '兵器の冠晶', sellPrice: 25 },
    { id: 'mat_regalia_sword', name: '神意の結晶剣', sellPrice: 150 },
    { id: 'mat_genesis_fragment', name: '創世の微光', sellPrice: 20 },
    { id: 'mat_genesis_core', name: '超存在の立方核', sellPrice: 40 },
    { id: 'mat_genesis_light', name: '万象のプリズム光', sellPrice: 200 }
].map(item => ({ ...item, image: `./assets/material/${item.id}.webp` }));
