/**
 * このファイルは素材やドロップアイテムなど、装備できないアイテムのデータをまとめたファイルです。
 * 
 * 素材・消費アイテムなどのデータ定義ファイル
 * 
 * 装備できないアイテム（モンスターのドロップ品など）を定義します。
 */

export const MATERIALS = [
  // スライムの森
  { id: 'slime_blue_jelly'      , name: 'ブルースライムのゼリー'          , sellPrice:   1 },
  { id: 'slime_blue_core'       , name: 'ブルースライムのコア'            , sellPrice:   1 },
  { id: 'slime_blue_fluid'      , name: 'ブルースライムの体液'            , sellPrice:   1 },
  { id: 'slime_green_jelly'     , name: 'グリーンスライムのゼリー'        , sellPrice:   1 },
  { id: 'slime_green_core'      , name: 'グリーンスライムのコア'          , sellPrice:   1 },
  { id: 'slime_green_fluid'     , name: 'グリーンスライムの体液'          , sellPrice:   1 },
  { id: 'slime_red_jelly'       , name: 'レッドスライムのゼリー'          , sellPrice:   1 },
  { id: 'slime_red_core'        , name: 'レッドスライムのコア'            , sellPrice:   1 },
  { id: 'slime_red_fluid'       , name: 'レッドスライムの体液'            , sellPrice:   1 },
  { id: 'slime_water_jelly'     , name: 'ウォータースライムのゼリー'      , sellPrice:   1 },
  { id: 'slime_water_core'      , name: 'ウォータースライムのコア'        , sellPrice:   1 },
  { id: 'slime_water_fluid'     , name: 'ウォータースライムの体液'        , sellPrice:   1 },
  { id: 'slime_fire_jelly'      , name: 'ファイヤースライムのゼリー'      , sellPrice:   1 },
  { id: 'slime_fire_core'       , name: 'ファイヤースライムのコア'        , sellPrice:   1 },
  { id: 'slime_fire_fluid'      , name: 'ファイヤースライムの体液'        , sellPrice:   1 },
  { id: 'slime_ice_jelly'       , name: 'アイススライムのゼリー'          , sellPrice:   1 },
  { id: 'slime_ice_core'        , name: 'アイススライムのコア'            , sellPrice:   1 },
  { id: 'slime_ice_fluid'       , name: 'アイススライムの体液'            , sellPrice:   1 },
  { id: 'slime_wind_jelly'      , name: 'ウインドスライムのゼリー'        , sellPrice:   1 },
  { id: 'slime_wind_core'       , name: 'ウインドスライムのコア'          , sellPrice:   1 },
  { id: 'slime_wind_fluid'      , name: 'ウインドスライムの体液'          , sellPrice:   1 },
  { id: 'slime_thunder_jelly'   , name: 'サンダースライムのゼリー'        , sellPrice:   1 },
  { id: 'slime_thunder_core'    , name: 'サンダースライムのコア'          , sellPrice:   1 },
  { id: 'slime_thunder_fluid'   , name: 'サンダースライムの体液'          , sellPrice:   1 },
  { id: 'slime_flower_jelly'    , name: 'フラワースライムのゼリー'        , sellPrice:   1 },
  { id: 'slime_flower_core'     , name: 'フラワースライムのコア'          , sellPrice:   1 },
  { id: 'slime_flower_fluid'    , name: 'フラワースライムの体液'          , sellPrice:   1 },
  { id: 'slime_grass_jelly'     , name: 'グラススライムのゼリー'          , sellPrice:   1 },
  { id: 'slime_grass_core'      , name: 'グラススライムのコア'            , sellPrice:   1 },
  { id: 'slime_grass_fluid'     , name: 'グラススライムの体液'            , sellPrice:   1 },
  { id: 'slime_dark_jelly'      , name: 'ダークスライムのゼリー'          , sellPrice:   1 },
  { id: 'slime_dark_core'       , name: 'ダークスライムのコア'            , sellPrice:   1 },
  { id: 'slime_dark_fluid'      , name: 'ダークスライムの体液'            , sellPrice:   1 },
  { id: 'slime_earth_jelly'     , name: 'アーススライムのゼリー'          , sellPrice:   1 },
  { id: 'slime_earth_core'      , name: 'アーススライムのコア'            , sellPrice:   1 },
  { id: 'slime_earth_fluid'     , name: 'アーススライムの体液'            , sellPrice:   1 },
  { id: 'slime_angel_jelly'     , name: 'エンジェルスライムのゼリー'      , sellPrice:   1 },
  { id: 'slime_angel_core'      , name: 'エンジェルスライムのコア'        , sellPrice:   1 },
  { id: 'slime_angel_fluid'     , name: 'エンジェルスライムの体液'        , sellPrice:   1 },
  { id: 'slime_king_jelly'      , name: 'キングスライムのゼリー'          , sellPrice:   1 },
  { id: 'slime_king_core'       , name: 'キングスライムのコア'            , sellPrice:   1 },
  { id: 'slime_king_fluid'      , name: 'キングスライムの体液'            , sellPrice:   1 },
  { id: 'slime_angel_king_jelly', name: 'エンジェルキングスライムのゼリー', sellPrice:   1 },
  { id: 'slime_angel_king_core' , name: 'エンジェルキングスライムのコア'  , sellPrice:   1 },
  { id: 'slime_angel_king_fluid', name: 'エンジェルキングスライムの体液'  , sellPrice:   1 },
  { id: 'slime_amethyst_shard'  , name: 'アメジストの欠片'                , sellPrice:  10 },
  { id: 'slime_amethyst_crystal', name: '紫水晶の結晶'                    , sellPrice:  50 },
  { id: 'slime_amethyst_heart'  , name: '紫光の心臓'                      , sellPrice: 200 },
  { id: 'slime_tiger_eye_stone' , name: '虎目石の欠片'                    , sellPrice:  10 },
  { id: 'slime_tiger_eye_fang'  , name: '虎の牙'                          , sellPrice:  50 },
  { id: 'slime_tiger_eye_soul'  , name: '猛虎の魂'                        , sellPrice: 200 },
  { id: 'slime_king_devil_horn' , name: '悪魔王の角'                      , sellPrice:  20 },
  { id: 'slime_king_devil_wing' , name: '悪魔王の翼膜'                    , sellPrice: 100 },
  { id: 'slime_king_devil_crown', name: '魔王の冠'                        , sellPrice: 500 },

  // 黄金のスライム島
  { id: 'mat_gold_slime_drop'      , name: '黄金の粘液'      , sellPrice: 1 },
  { id: 'mat_pure_gold_fluid'      , name: '純金の体液'      , sellPrice: 1 },
  { id: 'mat_golden_core'          , name: '黄金の核'        , sellPrice: 1 },
  { id: 'mat_gold_king_jelly'      , name: '王者の黄金ゼリー', sellPrice: 1 },
  { id: 'mat_gold_king_crown_shard', name: '黄金王の冠片'    , sellPrice: 1 },
  { id: 'mat_royal_gold_core'      , name: '豪奢な王核'      , sellPrice: 1 },
  { id: 'mat_gold_kaiser_fluid'    , name: '皇帝の黄金液'    , sellPrice: 1 },
  { id: 'mat_kaiser_gold_crown'    , name: '皇帝の黄金冠'    , sellPrice: 1 },
  { id: 'mat_emperor_gold_core'    , name: '帝王の神聖核'    , sellPrice: 1 },

  // 蜘蛛の洞窟
  { id: 'spider_cave_silk'      , name: 'ケイブスパイダーの糸'        , sellPrice: 1 },
  { id: 'spider_cave_fang'      , name: 'ケイブスパイダーの牙'        , sellPrice: 1 },
  { id: 'spider_cave_venom'     , name: 'ケイブスパイダーの毒液'      , sellPrice: 1 },
  { id: 'spider_poison_silk'    , name: 'ポイズンスパイダーの糸'      , sellPrice: 1 },
  { id: 'spider_poison_fang'    , name: 'ポイズンスパイダーの牙'      , sellPrice: 1 },
  { id: 'spider_poison_venom'   , name: 'ポイズンスパイダーの毒液'    , sellPrice: 1 },
  { id: 'spider_trapdoor_silk'  , name: 'トラップドアスパイダーの糸'  , sellPrice: 1 },
  { id: 'spider_trapdoor_fang'  , name: 'トラップドアスパイダーの牙'  , sellPrice: 1 },
  { id: 'spider_trapdoor_venom' , name: 'トラップドアスパイダーの毒液', sellPrice: 1 },
  { id: 'weaver_web_silk'       , name: 'ウェブウィーバーの糸'        , sellPrice: 1 },
  { id: 'weaver_web_fang'       , name: 'ウェブウィーバーの牙'        , sellPrice: 1 },
  { id: 'weaver_web_venom'      , name: 'ウェブウィーバーの毒液'      , sellPrice: 1 },
  { id: 'spitter_acid_silk'     , name: 'アシッドスピッターの糸'      , sellPrice: 1 },
  { id: 'spitter_acid_fang'     , name: 'アシッドスピッターの牙'      , sellPrice: 1 },
  { id: 'spitter_acid_venom'    , name: 'アシッドスピッターの毒液'    , sellPrice: 1 },
  { id: 'arachnid_shadow_silk'  , name: 'シャドウアラクニドの糸'      , sellPrice: 1 },
  { id: 'arachnid_shadow_fang'  , name: 'シャドウアラクニドの牙'      , sellPrice: 1 },
  { id: 'arachnid_shadow_venom' , name: 'シャドウアラクニドの毒液'    , sellPrice: 1 },
  { id: 'tick_blood_silk'       , name: 'ブラッドティックの糸'        , sellPrice: 1 },
  { id: 'tick_blood_fang'       , name: 'ブラッドティックの牙'        , sellPrice: 1 },
  { id: 'tick_blood_venom'      , name: 'ブラッドティックの毒液'      , sellPrice: 1 },
  { id: 'crawler_bone_silk'     , name: 'ボーンクロウラーの糸'        , sellPrice: 1 },
  { id: 'crawler_bone_fang'     , name: 'ボーンクロウラーの牙'        , sellPrice: 1 },
  { id: 'crawler_bone_venom'    , name: 'ボーンクロウラーの毒液'      , sellPrice: 1 },
  { id: 'swarm_spider_silk'     , name: 'スパイダースウォームの糸'    , sellPrice: 1 },
  { id: 'swarm_spider_fang'     , name: 'スパイダースウォームの牙'    , sellPrice: 1 },
  { id: 'swarm_spider_venom'    , name: 'スパイダースウォームの毒液'  , sellPrice: 1 },
  { id: 'spider_dark_silk'      , name: 'ダークウィドウの糸'          , sellPrice: 1 },
  { id: 'spider_dark_fang'      , name: 'ダークウィドウの牙'          , sellPrice: 1 },
  { id: 'spider_dark_venom'     , name: 'ダークウィドウの毒液'        , sellPrice: 1 },
  { id: 'weaver_golden_silk'    , name: 'ゴールデンウィーバーの糸'    , sellPrice: 1 },
  { id: 'weaver_golden_fang'    , name: 'ゴールデンウィーバーの牙'    , sellPrice: 1 },
  { id: 'weaver_golden_venom'   , name: 'ゴールデンウィーバーの毒液'  , sellPrice: 1 },
  { id: 'arachnid_crystal_silk' , name: 'クリスタルアラクニドの糸'    , sellPrice: 1 },
  { id: 'arachnid_crystal_fang' , name: 'クリスタルアラクニドの牙'    , sellPrice: 1 },
  { id: 'arachnid_crystal_venom', name: 'クリスタルアラクニドの毒液'  , sellPrice: 1 },
  { id: 'boss_broodmother_silk' , name: 'ブルードマザーの糸'          , sellPrice: 1 },
  { id: 'boss_broodmother_fang' , name: 'ブルードマザーの牙'          , sellPrice: 1 },
  { id: 'boss_broodmother_venom', name: 'ブルードマザーの毒液'        , sellPrice: 1 },
  { id: 'boss_arachne_silk'     , name: 'アラクネ・クイーンの糸'      , sellPrice: 1 },
  { id: 'boss_arachne_fang'     , name: 'アラクネ・クイーンの牙'      , sellPrice: 1 },
  { id: 'boss_arachne_venom'    , name: 'アラクネ・クイーンの毒液'    , sellPrice: 1 },
  { id: 'boss_deathweaver_silk' , name: 'デスウィーバーの糸'          , sellPrice: 1 },
  { id: 'boss_deathweaver_fang' , name: 'デスウィーバーの牙'          , sellPrice: 1 },
  { id: 'boss_deathweaver_venom', name: 'デスウィーバーの毒液'        , sellPrice: 1 },

  // クリスタルの洞窟
  { id: 'mat_crisp_shard'            , name: 'クリスプの欠片'      , sellPrice: 1 },
  { id: 'mat_crisp_core'             , name: 'クリスプの核'        , sellPrice: 1 },
  { id: 'mat_crisp_resonance_crystal', name: '共鳴する水明石'      , sellPrice: 1 },
  { id: 'mat_geode_shell'            , name: 'ジオードの甲羅'      , sellPrice: 1 },
  { id: 'mat_geode_amethyst'         , name: '紫水晶の原石'        , sellPrice: 1 },
  { id: 'mat_geode_heart'            , name: 'ジオードの心臓'      , sellPrice: 1 },
  { id: 'mat_snow_crystal'           , name: '雪花の結晶'          , sellPrice: 1 },
  { id: 'mat_snow_frog_dust'         , name: '氷精の粉'            , sellPrice: 1 },
  { id: 'mat_snow_frog_spirit'       , name: '絶対零度の核'        , sellPrice: 1 },
  { id: 'mat_crystalinos_horn'       , name: 'クリスタライノスの角', sellPrice: 1 },
  { id: 'mat_crystalinos_armor'      , name: '砕けない水晶装甲'    , sellPrice: 1 },
  { id: 'mat_crystalinos_soul'       , name: '巨獣の結晶魂'        , sellPrice: 1 },
  { id: 'mat_garnet_fang'            , name: '柘榴石の牙'          , sellPrice: 1 },
  { id: 'mat_garnet_pelt'            , name: '紅玉狼の毛皮'        , sellPrice: 1 },
  { id: 'mat_garnet_eye'             , name: 'ガーネットの血瞳'    , sellPrice: 1 },
  { id: 'mat_amber_scale'            , name: '琥珀の鱗'            , sellPrice: 1 },
  { id: 'mat_amber_venom'            , name: '太古の猛毒液'        , sellPrice: 1 },
  { id: 'mat_amber_fossil'           , name: '完全な琥珀化石'      , sellPrice: 1 },
  { id: 'mat_beryl_stone'            , name: '緑柱石の塊'          , sellPrice: 1 },
  { id: 'mat_beryl_core'             , name: '遺跡守護者の動力核'  , sellPrice: 1 },
  { id: 'mat_beryl_reactor'          , name: 'ベリルリアクター'    , sellPrice: 1 },
  { id: 'mat_jewel_wing'             , name: '宝石の翅'            , sellPrice: 1 },
  { id: 'mat_jewel_blade'            , name: '金剛石の鎌刃'        , sellPrice: 1 },
  { id: 'mat_jewel_diamond'          , name: '完全無欠のダイヤ'    , sellPrice: 1 },
  { id: 'mat_fluorite_powder'        , name: '蛍石の鱗粉'          , sellPrice: 1 },
  { id: 'mat_fluorite_wing'          , name: '幻惑の蝶翅'          , sellPrice: 1 },
  { id: 'mat_fluorite_illusion'      , name: '無限の幻夢結晶'      , sellPrice: 1 },
  { id: 'mat_pyrite_scale'           , name: '黄鉄鉱の鱗'          , sellPrice: 1 },
  { id: 'mat_pyrite_fang'            , name: '愚者の毒牙'          , sellPrice: 1 },
  { id: 'mat_pyrite_fool_gold'       , name: '真なる愚者の黄金'    , sellPrice: 1 },
  { id: 'mat_luminous_leaf'          , name: '光樹の葉'            , sellPrice: 1 },
  { id: 'mat_luminous_sap'           , name: '光満ちる樹液'        , sellPrice: 1 },
  { id: 'mat_luminous_flower'        , name: 'ジギタリスの極光花'  , sellPrice: 1 },
  { id: 'mat_opal_dust'              , name: 'オパールの砂'        , sellPrice: 1 },
  { id: 'mat_opal_fragment'          , name: '遊色の欠片'          , sellPrice: 1 },
  { id: 'mat_opal_chaos'             , name: '混沌のオパール核'    , sellPrice: 1 },
  { id: 'mat_diamond_scale'          , name: '金剛竜の鱗'          , sellPrice: 1 },
  { id: 'mat_diamond_claw'           , name: '金剛竜の光爪'        , sellPrice: 1 },
  { id: 'mat_diamond_laser_core'     , name: '極大光線の竜核'      , sellPrice: 1 },
  { id: 'mat_regalia_shard'          , name: '王権の破片'          , sellPrice: 1 },
  { id: 'mat_regalia_crown'          , name: '兵器の冠晶'          , sellPrice: 1 },
  { id: 'mat_regalia_sword'          , name: '神意の結晶剣'        , sellPrice: 1 },
  { id: 'mat_genesis_fragment'       , name: '創世の微光'          , sellPrice: 1 },
  { id: 'mat_genesis_core'           , name: '超存在の立方核'      , sellPrice: 1 },
  { id: 'mat_genesis_light'          , name: '万象のプリズム光'    , sellPrice: 1 },

  // 亡霊の廃城
  { id: 'mat_rust_armor'        , name: '錆びついた近衛鎧'  , sellPrice: 1 },
  { id: 'mat_rust_sword'        , name: 'ボロボロの直剣'    , sellPrice: 1 },
  { id: 'mat_grudge_soul'       , name: '怨念の塊'          , sellPrice: 1 },
  { id: 'mat_dust_cloth'        , name: '塵埃の布切れ'      , sellPrice: 1 },
  { id: 'mat_maid_broom'        , name: '折れた箒'          , sellPrice: 1 },
  { id: 'mat_spider_web'        , name: '古びた蜘蛛の巣'    , sellPrice: 1 },
  { id: 'mat_cursed_glass'      , name: '呪われたガラス片'  , sellPrice: 1 },
  { id: 'mat_blue_flame'        , name: '消えない青炎'      , sellPrice: 1 },
  { id: 'mat_heavy_chain'       , name: '重たい鎖'          , sellPrice: 1 },
  { id: 'mat_forbidden_page'    , name: '禁書の切れ端'      , sellPrice: 1 },
  { id: 'mat_magic_ink'         , name: '狂気を孕むインク'  , sellPrice: 1 },
  { id: 'mat_madness_cover'     , name: '魔導書の表紙'      , sellPrice: 1 },
  { id: 'mat_old_canvas'        , name: '古ぼけたキャンバス', sellPrice: 1 },
  { id: 'mat_gold_frame'        , name: '金色の額縁'        , sellPrice: 1 },
  { id: 'mat_hollow_eye'        , name: '虚ろな絵の具'      , sellPrice: 1 },
  { id: 'mat_shadow_fur'        , name: '影の毛皮'          , sellPrice: 1 },
  { id: 'mat_hound_fang'        , name: '猟犬の黒牙'        , sellPrice: 1 },
  { id: 'mat_dark_collar'       , name: '闇染みの首輪'      , sellPrice: 1 },
  { id: 'mat_rat_tail'          , name: '変異鼠の尻尾'      , sellPrice: 1 },
  { id: 'mat_corpse_flesh'      , name: '屍肉の塊'          , sellPrice: 1 },
  { id: 'mat_plague_blood'      , name: '伝染病の血液'      , sellPrice: 1 },
  { id: 'mat_pure_gold'         , name: '純金の欠片'        , sellPrice: 1 },
  { id: 'mat_glitter_gem'       , name: '輝く宝玉'          , sellPrice: 1 },
  { id: 'mat_lost_treasure'     , name: '置き去りの財宝'    , sellPrice: 1 },
  { id: 'mat_broken_crown'      , name: '崩れた王冠'        , sellPrice: 1 },
  { id: 'mat_grudge_greatsword' , name: '怨讐の大剣'        , sellPrice: 1 },
  { id: 'mat_king_soul'         , name: '廃王の魂'          , sellPrice: 1 },
  { id: 'mat_forbidden_grimoire', name: '禁断の降霊術書'    , sellPrice: 1 },
  { id: 'mat_necromancer_robe'  , name: '屍術師の法衣'      , sellPrice: 1 },
  { id: 'mat_origin_core'       , name: '災厄の根源核'      , sellPrice: 1 },

  // 精霊の唄う谷
  { id: 'mat_humming_leaf_vein'    , name: 'ハミングリーフの葉脈'  , sellPrice: 1 },
  { id: 'mat_wind_song_dew'        , name: '風詠みの朝露'          , sellPrice: 1 },
  { id: 'mat_spirit_leaf_fossil'   , name: '精霊葉の化石'          , sellPrice: 1 },
  { id: 'mat_glow_bug_shell'       , name: '音色蛍の殻'            , sellPrice: 1 },
  { id: 'mat_resonance_phosphorus' , name: '共鳴する燐光'          , sellPrice: 1 },
  { id: 'mat_eternal_light_core'   , name: '常夜灯の核'            , sellPrice: 1 },
  { id: 'mat_pixie_dust'           , name: 'ピクシーダスト'        , sellPrice: 1 },
  { id: 'mat_breeze_wing'          , name: 'そよ風の羽'            , sellPrice: 1 },
  { id: 'mat_fairy_wind_stone'     , name: '妖風石'                , sellPrice: 1 },
  { id: 'mat_singing_root'         , name: '唄う根菜'              , sellPrice: 1 },
  { id: 'mat_mandragora_leaf'      , name: 'マンドラゴラの若葉'    , sellPrice: 1 },
  { id: 'mat_choir_seed'           , name: '合唱の種子'            , sellPrice: 1 },
  { id: 'mat_bell_feather'         , name: '鈴鳴りの羽'            , sellPrice: 1 },
  { id: 'mat_swallow_beak'         , name: '大ツバメの嘴'          , sellPrice: 1 },
  { id: 'mat_chime_crystal'        , name: '風鈴晶'                , sellPrice: 1 },
  { id: 'mat_echo_ectoplasm'       , name: 'エコーエクトプラズム'  , sellPrice: 1 },
  { id: 'mat_wisp_flame'           , name: 'ウィスプの残り火'      , sellPrice: 1 },
  { id: 'mat_reverberating_soul'   , name: '反響する魂'            , sellPrice: 1 },
  { id: 'mat_flute_scale'          , name: 'フルートの鱗'          , sellPrice: 1 },
  { id: 'mat_lizard_throat'        , name: '蜥蜴の鳴袋'            , sellPrice: 1 },
  { id: 'mat_wind_dragon_horn'     , name: '風竜の角片'            , sellPrice: 1 },
  { id: 'mat_sylph_garment'        , name: 'シルフの羽衣'          , sellPrice: 1 },
  { id: 'mat_melody_orb'           , name: '旋律のオーブ'          , sellPrice: 1 },
  { id: 'mat_sylphid_heart'        , name: '風精の心臓'            , sellPrice: 1 },
  { id: 'mat_water_chime_jelly'    , name: '水琴のゼリー'          , sellPrice: 1 },
  { id: 'mat_echo_water'           , name: '反響水'                , sellPrice: 1 },
  { id: 'mat_suikinkutsu_core'     , name: '水琴窟の核'            , sellPrice: 1 },
  { id: 'mat_treant_bark'          , name: '木魂の樹皮'            , sellPrice: 1 },
  { id: 'mat_kodama_branch'        , name: 'こだまの枝'            , sellPrice: 1 },
  { id: 'mat_spirit_wood_heart'    , name: '霊木の心材'            , sellPrice: 1 },
  { id: 'mat_griffon_feather'      , name: '詠唱者の羽'            , sellPrice: 1 },
  { id: 'mat_chanting_beak'        , name: '呪詛の嘴'              , sellPrice: 1 },
  { id: 'mat_hymn_talon'           , name: '聖歌の爪'              , sellPrice: 1 },
  { id: 'mat_siren_scale'          , name: 'セイレーンの鱗'        , sellPrice: 1 },
  { id: 'mat_phantom_tear'         , name: '幻涙'                  , sellPrice: 1 },
  { id: 'mat_mermaid_voice_jewel'  , name: '人魚の美声石'          , sellPrice: 1 },
  { id: 'mat_resonance_stone'      , name: '共鳴石'                , sellPrice: 1 },
  { id: 'mat_golem_joint'          , name: 'ゴーレムの関節'        , sellPrice: 1 },
  { id: 'mat_vibrating_core'       , name: '振動核'                , sellPrice: 1 },
  { id: 'mat_harp_scale'           , name: 'ハープの鱗'            , sellPrice: 1 },
  { id: 'mat_gale_fang'            , name: '狂風の牙'              , sellPrice: 1 },
  { id: 'mat_dragon_string'        , name: '竜の弦'                , sellPrice: 1 },
  { id: 'mat_requiem_water'        , name: '鎮魂の清水'            , sellPrice: 1 },
  { id: 'mat_undine_veil'          , name: 'ウンディーネのヴェール', sellPrice: 1 },
  { id: 'mat_spirit_tear_crystal'  , name: '精霊の涙晶'            , sellPrice: 1 },
  { id: 'mat_white_deer_fur'       , name: '白鹿の毛皮'            , sellPrice: 1 },
  { id: 'mat_hymn_antler'          , name: '聖歌の枝角'            , sellPrice: 1 },
  { id: 'mat_sacred_hoof'          , name: '神聖な蹄'              , sellPrice: 1 },
  { id: 'mat_storm_feather'        , name: '嵐の羽'                , sellPrice: 1 },
  { id: 'mat_thunder_bird_beak'    , name: '雷鳥の嘴'              , sellPrice: 1 },
  { id: 'mat_tempest_eye'          , name: '暴風の目'              , sellPrice: 1 },
  { id: 'mat_spirit_knight_armor'  , name: '精霊騎士の甲冑片'      , sellPrice: 1 },
  { id: 'mat_swan_song_blade'      , name: '絶唱の刃'              , sellPrice: 1 },
  { id: 'mat_knight_soul_stone'    , name: '騎士の魂石'            , sellPrice: 1 },
  { id: 'mat_echo_dragon_scale'    , name: '響竜の鱗'              , sellPrice: 1 },
  { id: 'mat_eternal_fang'         , name: '悠久の牙'              , sellPrice: 1 },
  { id: 'mat_resonance_dragon_core', name: '共鳴竜の逆鱗'          , sellPrice: 1 },
  { id: 'mat_genesis_song_fragment', name: '創世の唄の欠片'        , sellPrice: 1 },
  { id: 'mat_creation_tear'        , name: '創造の涙'              , sellPrice: 1 },
  { id: 'mat_origin_melody_crystal', name: '始源の旋律結晶'        , sellPrice: 1 },
  
  // スペシャルダンジョン: 鉱山
  { id: 'mat_copper_ore', name: '銅鉱石', sellPrice: 1 },
  { id: 'mat_cuprite', name: '赤銅鉱', sellPrice: 1 },
  { id: 'mat_native_copper', name: '自然銅', sellPrice: 1 },
  { id: 'mat_tin_ore', name: '錫鉱石', sellPrice: 1 },
  { id: 'mat_cassiterite', name: '錫石', sellPrice: 1 },
  { id: 'mat_pure_tin', name: '純錫鉱', sellPrice: 1 },
  { id: 'mat_iron_ore', name: '鉄鉱石', sellPrice: 1 },
  { id: 'mat_magnetite', name: '磁鉄鉱', sellPrice: 1 },
  { id: 'mat_pure_iron', name: '純鉄鉱', sellPrice: 1 },
  { id: 'mat_coal_ore', name: '石炭鉱', sellPrice: 1 },
  { id: 'mat_anthracite', name: '無煙炭', sellPrice: 1 },
  { id: 'mat_black_diamond', name: '黒金剛石', sellPrice: 1 },
  { id: 'mat_silver_ore', name: '銀鉱石', sellPrice: 1 },
  { id: 'mat_argentite', name: '輝銀鉱', sellPrice: 1 },
  { id: 'mat_pure_silver', name: '純銀鉱', sellPrice: 1 },
  { id: 'mat_gold_ore', name: '金鉱石', sellPrice: 1 },
  { id: 'mat_calaverite', name: 'カラベラス鉱', sellPrice: 1 },
  { id: 'mat_pure_gold_nugget', name: '純金鉱塊', sellPrice: 1 },
  { id: 'mat_quartz_ore', name: '石英鉱石', sellPrice: 1 },
  { id: 'mat_smoky_quartz', name: '煙水晶', sellPrice: 1 },
  { id: 'mat_phantom_quartz', name: '幻影石英', sellPrice: 1 },
  { id: 'mat_jade_ore', name: '翡翠原石', sellPrice: 1 },
  { id: 'mat_nephrite', name: '軟玉鉱', sellPrice: 1 },
  { id: 'mat_imperial_jade', name: '帝王翡翠', sellPrice: 1 },
  { id: 'mat_cobalt_ore', name: 'コバルト鉱石', sellPrice: 1 },
  { id: 'mat_cobaltite', name: 'コバルト華', sellPrice: 1 },
  { id: 'mat_cobalt_crystal', name: '蒼晶コバルト', sellPrice: 1 },
  { id: 'mat_mithril_ore', name: 'ミスリル鉱石', sellPrice: 1 },
  { id: 'mat_mithril_ingot', name: 'ミスリル鉱塊', sellPrice: 1 },
  { id: 'mat_true_mithril', name: '真ミスリル晶', sellPrice: 1 },
  { id: 'mat_orichalcum_ore', name: 'オリハルコン鉱石', sellPrice: 1 },
  { id: 'mat_orichalcum_ingot', name: 'オリハルコン鉱塊', sellPrice: 1 },
  { id: 'mat_orichalcum_core', name: '神鋼鉱核', sellPrice: 1 },
  { id: 'mat_adamantite_ore', name: 'アダマンタイト鉱石', sellPrice: 1 },
  { id: 'mat_adamantite_plate', name: '金剛鉱板', sellPrice: 1 },
  { id: 'mat_adamantite_heart', name: '不壊鉱心', sellPrice: 1 },
  { id: 'mat_uranium_ore', name: 'ウラニウム鉱石', sellPrice: 1 },
  { id: 'mat_pitchblende', name: '瀝青ウラン鉱', sellPrice: 1 },
  { id: 'mat_radiant_uranium', name: '輝放鉱晶', sellPrice: 1 },
  { id: 'mat_star_metal_ore', name: '星鉄鉱石', sellPrice: 1 },
  { id: 'mat_meteoric_iron', name: '隕鉄鉱', sellPrice: 1 },
  { id: 'mat_cosmic_alloy', name: '天宙合金鉱', sellPrice: 1 },
  { id: 'mat_motherlode_ore', name: '大鉱脈原石', sellPrice: 1 },
  { id: 'mat_rainbow_ore', name: '虹色鉱石', sellPrice: 1 },
  { id: 'mat_primordial_ore_core', name: '始原鉱核', sellPrice: 1 },

  // 神秘の神殿
  { id: 'mat_aether_ore'            , name: 'エーテル鉱石'          , sellPrice: 1 },
  { id: 'mat_translucent_marble'    , name: '半透明の大理石'        , sellPrice: 1 },
  { id: 'mat_colossus_core'         , name: '巨像の動力核'          , sellPrice: 1 },
  { id: 'mat_mossy_stone'           , name: '苔生した岩片'          , sellPrice: 1 },
  { id: 'mat_monolith_fragment'     , name: '一枚岩の欠片'          , sellPrice: 1 },
  { id: 'mat_aegis_shield_piece'    , name: '神盾の破片'            , sellPrice: 1 },
  { id: 'mat_gigas_clay'            , name: 'ギガースの土塊'        , sellPrice: 1 },
  { id: 'mat_glowing_rune_stone'    , name: '発光するルーン石'      , sellPrice: 1 },
  { id: 'mat_ancient_priest_scroll' , name: '古代神官の巻物'        , sellPrice: 1 },
  { id: 'mat_obsidian_shard'        , name: '黒曜石の鋭片'          , sellPrice: 1 },
  { id: 'mat_xenolith_meteorite'    , name: 'ゼノリス隕石'          , sellPrice: 1 },
  { id: 'mat_guardian_eye'          , name: '守護者の黒眼'          , sellPrice: 1 },
  { id: 'mat_temple_pillar_fragment', name: '神殿柱の破片'          , sellPrice: 1 },
  { id: 'mat_altar_stone'           , name: '祭壇の石材'            , sellPrice: 1 },
  { id: 'mat_basilica_foundation'   , name: '大聖堂の礎'            , sellPrice: 1 },
  { id: 'mat_temple_crystal'        , name: '神殿の魔結晶'          , sellPrice: 1 },
  { id: 'mat_magic_reflect_prism'   , name: '魔反射のプリズム'      , sellPrice: 1 },
  { id: 'mat_crystallos_heart'      , name: 'クリスタロスの心核'    , sellPrice: 1 },
  { id: 'mat_machina_gear'          , name: 'マキナの歯車'          , sellPrice: 1 },
  { id: 'mat_four_armed_joint'      , name: '四腕の関節機構'        , sellPrice: 1 },
  { id: 'mat_atlas_support_pillar'  , name: '天を支える支柱'        , sellPrice: 1 },
  { id: 'mat_sacred_bronze'         , name: '神聖なる青銅'          , sellPrice: 1 },
  { id: 'mat_talos_armor_plate'     , name: 'タロスの装甲板'        , sellPrice: 1 },
  { id: 'mat_sanctum_key_fragment'  , name: '至聖所の鍵の欠片'      , sellPrice: 1 }
].map(item => ({ ...item, image: `./assets/material/${item.id}.webp` }));
