/**
 * このファイルは敵として登場するモンスターの強さや、落とすアイテムなどのデータをまとめたファイルです。
 * 
 * モンスターのデータ定義ファイル
 * 
 * 敵キャラクターとして出現するモンスターのステータスやドロップアイテムを定義します。
 * 
 * テンプレート（各項目は省略可能、省略された値は 0 として扱われます）
 *    stats: { hp:    0, atk:   1, def:   1, matk:   1, mdef:   1, spd:   1 },
 *    elements:      { fire: 0, water: 0, grass: 0, ice: 0, thunder: 0, wind: 0, earth: 0, light: 0, dark: 0 },
 *    ailments:      { poison: 0, burn: 0, paralysis: 0, sleep: 0, confusion: 0, curse: 0, blind: 0, silence: 0 },
 */

function createSummonAction(actionName, summonPoolIds, getMonsters) {
  return (attacker, defender, battle) => {
    const MONSTERS = getMonsters();
    const leftDef = MONSTERS.find(m => m.id === summonPoolIds[Math.floor(Math.random() * summonPoolIds.length)]);
    const rightDef = MONSTERS.find(m => m.id === summonPoolIds[Math.floor(Math.random() * summonPoolIds.length)]);
    if (leftDef && rightDef) {
      battle.showActionName(attacker.elementId, actionName, 'text-purple-300', 'border-purple-500/50');
      const createEnemy = (mDef, suffix) => {
        const baseStats = { hp: 0, atk: 0, def: 0, matk: 0, mdef: 0, spd: 0, ...(mDef.stats || {}) };
        return {
          ...mDef,
          stats: {
            ...baseStats,
            attackElements: { fire: 0, water: 0, grass: 0, ice: 0, thunder: 0, wind: 0, earth: 0, light: 0, dark: 0 },
            attackAilments: { poison: 0, burn: 0, paralysis: 0, sleep: 0, confusion: 0, curse: 0, blind: 0, silence: 0 },
            elementResist: { fire: 0, water: 0, grass: 0, ice: 0, thunder: 0, wind: 0, earth: 0, light: 0, dark: 0, ...(mDef.elements || {}) },
            ailmentResist: { poison: 0, burn: 0, paralysis: 0, sleep: 0, confusion: 0, curse: 0, blind: 0, silence: 0, ...(mDef.ailments || {}) }
          },
          uniqueId: `enemy-summon-${Date.now()}-${suffix}`,
          currentHp: baseStats.hp,
          hp: { current: baseStats.hp, max: baseStats.hp },
          maxHp: baseStats.hp,
          atb: 0,
          isDead: false,
          elementId: `enemy-summon-${Date.now()}-${suffix}`
        };
      };
      const attackerIdx = battle.enemies.indexOf(attacker);
      if (attackerIdx !== -1) {
        battle.enemies.splice(attackerIdx, 0, createEnemy(leftDef, 'L'));
        battle.enemies.splice(attackerIdx + 2, 0, createEnemy(rightDef, 'R'));
      } else {
        battle.enemies.push(createEnemy(leftDef, 'L'), createEnemy(rightDef, 'R'));
      }
      attacker.atb = 0;
      battle.elements.enemyArea.innerHTML = '';
      battle.renderEntities();
    }
  };
}

function createAilmentAttack(ailment, chance, actionName, multiplier = 1.2) {
  return (attacker, defender, battle) => {
    const origAilments = attacker.stats.attackAilments;
    attacker.stats.attackAilments = { ...(origAilments || {}), [ailment]: chance };
    battle.executeAttack(attacker, defender, false, { actionName, damageMultiplier: multiplier, isMagic: false, damageType: 'skill' });
    attacker.stats.attackAilments = origAilments;
  };
}

export const MONSTERS = [
  { id: 'slime_blue'      , name: 'ブルースライム'          , stats: { hp:   56, atk:   2, def:   1, matk:   2, mdef:   1, spd:   1 }      , elements: { water:  50, thunder: -50, grass: -50 }, ailments: {               }        , rewards: { exp: 1, jp: 1, gold: 1 } , drops: [{ itemId: 'slime_blue_jelly',        rate:   5 }, { itemId: 'slime_blue_core',         rate:   1 }, { itemId: 'slime_blue_fluid',        rate: 0.1 }], actions: [{ name: 'スライムスプラッシュ', chance: 15, description: '水属性の魔法攻撃。', execute: (attacker, defender, battle) => { const orig = attacker.stats.attackElements; attacker.stats.attackElements = { water: 100 }; battle.executeAttack(attacker, defender, false, { actionName: 'スライムスプラッシュ', damageMultiplier: 1.2, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = orig; } }] },
  { id: 'slime_green'     , name: 'グリーンスライム'        , stats: { hp:  105, atk:  20, def:   2, matk:  20, mdef:   2, spd:   7 }      , elements: { grass:  50, fire: -50                }, ailments: { poison: 10    }        , rewards: { exp: 2, jp: 2, gold: 2 } , drops: [{ itemId: 'slime_green_jelly',       rate:   5 }, { itemId: 'slime_green_core',        rate:   1 }, { itemId: 'slime_green_fluid',       rate: 0.1 }], actions: [{ name: 'アシッドバブル', chance: 15, description: '草属性の魔法攻撃。対象に確率で毒を付与する。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; const origA = attacker.stats.attackAilments; attacker.stats.attackElements = { grass: 100 }; attacker.stats.attackAilments = { ...(origA || {}), poison: 30 }; battle.executeAttack(attacker, defender, false, { actionName: 'アシッドバブル', damageMultiplier: 1.0, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; attacker.stats.attackAilments = origA; } }] },
  { id: 'slime_red'       , name: 'レッドスライム'          , stats: { hp:  154, atk:  35, def:   2, matk:  29, mdef:   4, spd:   9 }      , elements: { fire:  50, water: -50                }, ailments: { burn: 10      }        , rewards: { exp: 3, jp: 3, gold: 3 } , drops: [{ itemId: 'slime_red_jelly',         rate:   5 }, { itemId: 'slime_red_core',          rate:   1 }, { itemId: 'slime_red_fluid',         rate: 0.1 }], actions: [{ name: 'ヒートタックル', chance: 15, description: '炎属性の強力な物理攻撃。自身も最大HPの10%の反動ダメージを受ける。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; attacker.stats.attackElements = { fire: 100 }; battle.executeAttack(attacker, defender, false, { actionName: 'ヒートタックル', damageMultiplier: 1.8, isMagic: false, damageType: 'skill' }); attacker.stats.attackElements = origE; const recoil = Math.floor(attacker.stats.hp * 0.1); attacker.currentHp = Math.max(1, attacker.currentHp - recoil); battle.showDamage(attacker.elementId, recoil, 'text-red-500'); } }] },
  { id: 'slime_water'     , name: 'ウォータースライム'      , stats: { hp:  243, atk:  35, def:   5, matk:  39, mdef:   5, spd:  11 }      , elements: { water:  50, thunder: -50, grass: -50 }, ailments: {               }        , rewards: { exp: 4, jp: 4, gold: 4 } , drops: [{ itemId: 'slime_water_jelly',       rate:   5 }, { itemId: 'slime_water_core',        rate:   1 }, { itemId: 'slime_water_fluid',       rate: 0.1 }], actions: [{ name: 'アクアヒール', chance: 15, description: 'ランダムな味方1体のHPを大きく回復する。', execute: (attacker, defender, battle) => { const aliveEnemies = battle.enemies.filter(e => !e.isDead); const target = aliveEnemies[Math.floor(Math.random() * aliveEnemies.length)]; const healAmount = Math.floor(attacker.stats.matk * 2); target.currentHp = Math.min(target.stats.hp, target.currentHp + healAmount); battle.showActionName(attacker.elementId, 'アクアヒール', 'text-blue-300', 'border-blue-500/50'); battle.showDamage(target.elementId, `+${healAmount}`, 'text-green-400'); } }] },
  { id: 'slime_fire'      , name: 'ファイヤースライム'      , stats: { hp:  252, atk:  48, def:   7, matk:  48, mdef:   7, spd:  14 }      , elements: { fire:  50, water: -50                }, ailments: { burn: 10      }        , rewards: { exp: 5, jp: 5, gold: 5 } , drops: [{ itemId: 'slime_fire_jelly',        rate:   5 }, { itemId: 'slime_fire_core',         rate:   1 }, { itemId: 'slime_fire_fluid',        rate: 0.1 }], actions: [{ name: 'フレイムバースト', chance: 15, description: '炎属性の魔法攻撃。対象に確率で火傷を付与する。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; const origA = attacker.stats.attackAilments; attacker.stats.attackElements = { fire: 100 }; attacker.stats.attackAilments = { ...(origA || {}), burn: 40 }; battle.executeAttack(attacker, defender, false, { actionName: 'フレイムバースト', damageMultiplier: 1.3, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; attacker.stats.attackAilments = origA; } }] },
  { id: 'slime_ice'       , name: 'アイススライム'          , stats: { hp:  217, atk:  58, def:   6, matk:  58, mdef:   6, spd:  16 }      , elements: { ice:  50, fire: -50                  }, ailments: { paralysis: 10 }        , rewards: { exp: 6, jp: 6, gold: 6 } , drops: [{ itemId: 'slime_ice_jelly',         rate:   5 }, { itemId: 'slime_ice_core',          rate:   1 }, { itemId: 'slime_ice_fluid',         rate: 0.1 }], actions: [{ name: 'フリーズスマッシュ', chance: 15, description: '氷属性の物理攻撃。対象に確率で麻痺を付与する。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; const origA = attacker.stats.attackAilments; attacker.stats.attackElements = { ice: 100 }; attacker.stats.attackAilments = { ...(origA || {}), paralysis: 40 }; battle.executeAttack(attacker, defender, false, { actionName: 'フリーズスマッシュ', damageMultiplier: 1.3, isMagic: false, damageType: 'skill' }); attacker.stats.attackElements = origE; attacker.stats.attackAilments = origA; } }] },
  { id: 'slime_wind'      , name: 'ウインドスライム'        , stats: { hp:  350, atk:  67, def:  10, matk:  67, mdef:  10, spd:  27 }      , elements: { wind:  50, ice: -50                  }, ailments: { blind: 10     }        , rewards: { exp: 7, jp: 7, gold: 7 } , drops: [{ itemId: 'slime_wind_jelly',        rate:   5 }, { itemId: 'slime_wind_core',         rate:   1 }, { itemId: 'slime_wind_fluid',        rate: 0.1 }], actions: [{ name: 'エアロカッター', chance: 20, description: '風属性の強力な魔法攻撃。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; attacker.stats.attackElements = { wind: 100 }; battle.executeAttack(attacker, defender, false, { actionName: 'エアロカッター', damageMultiplier: 1.5, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; } }] },
  { id: 'slime_thunder'   , name: 'サンダースライム'        , stats: { hp:  287, atk:  77, def:   8, matk:  77, mdef:   8, spd:  20 }      , elements: { thunder:  50, earth: -50             }, ailments: { paralysis: 10 }        , rewards: { exp: 8, jp: 8, gold: 8 } , drops: [{ itemId: 'slime_thunder_jelly',     rate:   5 }, { itemId: 'slime_thunder_core',      rate:   1 }, { itemId: 'slime_thunder_fluid',     rate: 0.1 }], actions: [{ name: 'パラライズショック', chance: 15, description: '雷属性の魔法攻撃。対象に高確率で麻痺を付与する。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; const origA = attacker.stats.attackAilments; attacker.stats.attackElements = { thunder: 100 }; attacker.stats.attackAilments = { ...(origA || {}), paralysis: 50 }; battle.executeAttack(attacker, defender, false, { actionName: 'パラライズショック', damageMultiplier: 1.2, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; attacker.stats.attackAilments = origA; } }] },
  { id: 'slime_flower'    , name: 'フラワースライム'        , stats: { hp:  322, atk:  86, def:   9, matk:  86, mdef:   9, spd:  22 }      , elements: { grass:  50, fire: -50                }, ailments: { sleep: 10     }        , rewards: { exp: 9, jp: 9, gold: 9 } , drops: [{ itemId: 'slime_flower_jelly',      rate:   5 }, { itemId: 'slime_flower_core',       rate:   1 }, { itemId: 'slime_flower_fluid',      rate: 0.1 }], actions: [{ name: '睡眠の花粉', chance: 15, description: '草属性の魔法攻撃。対象に確率で睡眠を付与する。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; const origA = attacker.stats.attackAilments; attacker.stats.attackElements = { grass: 100 }; attacker.stats.attackAilments = { ...(origA || {}), sleep: 40 }; battle.executeAttack(attacker, defender, false, { actionName: '睡眠の花粉', damageMultiplier: 1.0, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; attacker.stats.attackAilments = origA; } }] },
  { id: 'slime_grass'     , name: 'グラススライム'          , stats: { hp:  497, atk:  95, def:  14, matk:  95, mdef:  14, spd:  24 }      , elements: { grass:  50, fire: -50                }, ailments: { poison: 10    }        , rewards: { exp: 10, jp: 10, gold: 10 } , drops: [{ itemId: 'slime_grass_jelly',       rate:   5 }, { itemId: 'slime_grass_core',        rate:   1 }, { itemId: 'slime_grass_fluid',       rate: 0.1 }], actions: [{ name: 'リーフブレード', chance: 20, description: '草属性の強力な物理攻撃。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; attacker.stats.attackElements = { grass: 100 }; battle.executeAttack(attacker, defender, false, { actionName: 'リーフブレード', damageMultiplier: 1.8, isMagic: false, damageType: 'skill' }); attacker.stats.attackElements = origE; } }] },
  { id: 'slime_dark'      , name: 'ダークスライム'          , stats: { hp:  392, atk: 105, def:  11, matk: 105, mdef:  11, spd:  26 }      , elements: { dark:  50, light: -50                }, ailments: { curse: 10     }        , rewards: { exp: 11, jp: 11, gold: 11 } , drops: [{ itemId: 'slime_dark_jelly',        rate:   5 }, { itemId: 'slime_dark_core',         rate:   1 }, { itemId: 'slime_dark_fluid',        rate: 0.1 }], actions: [{ name: 'ダークドレイン', chance: 15, description: '闇属性の魔法攻撃。与えたダメージの半分のHPを回復する。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; attacker.stats.attackElements = { dark: 100 }; const prevHp = defender.currentHp; battle.executeAttack(attacker, defender, false, { actionName: 'ダークドレイン', damageMultiplier: 1.2, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; const damageDealt = prevHp - defender.currentHp; if (damageDealt > 0) { const heal = Math.floor(damageDealt * 0.5); attacker.currentHp = Math.min(attacker.stats.hp, attacker.currentHp + heal); battle.showDamage(attacker.elementId, `+${heal}`, 'text-green-400'); } } }] },
  { id: 'slime_earth'     , name: 'アーススライム'          , stats: { hp:  654, atk: 114, def:  22, matk: 114, mdef:  17, spd:  22 }      , elements: { earth:  50, wind: -50, grass: -50    }, ailments: {               }        , rewards: { exp: 12, jp: 12, gold: 12 }  , drops: [{ itemId: 'slime_earth_jelly',       rate:   5 }, { itemId: 'slime_earth_core',        rate:   1 }, { itemId: 'slime_earth_fluid',       rate: 0.1 }], actions: [{ name: 'マッドスロー', chance: 15, description: '土属性の魔法攻撃。対象に確率で暗闇を付与する。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; const origA = attacker.stats.attackAilments; attacker.stats.attackElements = { earth: 100 }; attacker.stats.attackAilments = { ...(origA || {}), blind: 40 }; battle.executeAttack(attacker, defender, false, { actionName: 'マッドスロー', damageMultiplier: 1.2, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; attacker.stats.attackAilments = origA; } }] },
  { id: 'slime_angel'     , name: 'エンジェルスライム'      , stats: { hp:  462, atk: 123, def:  13, matk: 123, mdef:  13, spd:  30 }      , elements: { light:  50, dark: -50                }, ailments: { silence: 10   }        , rewards: { exp: 13, jp: 13, gold: 13 }  , drops: [{ itemId: 'slime_angel_jelly',       rate:   5 }, { itemId: 'slime_angel_core',        rate:   1 }, { itemId: 'slime_angel_fluid',       rate: 0.1 }], actions: [{ name: 'ホーリーライト', chance: 15, description: '光属性の魔法攻撃。対象に確率で沈黙を付与する。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; const origA = attacker.stats.attackAilments; attacker.stats.attackElements = { light: 100 }; attacker.stats.attackAilments = { ...(origA || {}), silence: 40 }; battle.executeAttack(attacker, defender, false, { actionName: 'ホーリーライト', damageMultiplier: 1.2, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; attacker.stats.attackAilments = origA; } }] },
  { id: 'slime_king'      , name: 'キングスライム'          , stats: { hp: 2970, atk: 163, def:  41, matk: 163, mdef:  41, spd:  32 }      , elements: {                                      }, ailments: {               }        , rewards: { exp: 20, jp: 20, gold: 20 }  , drops: [{ itemId: 'slime_king_jelly',        rate:   5 }, { itemId: 'slime_king_core',         rate:   1 }, { itemId: 'slime_king_fluid',        rate: 0.1 }], actions: [{ name: 'キングプレス', chance: 15, description: '全体重をかけた強力な物理攻撃。', execute: (attacker, defender, battle) => { battle.executeAttack(attacker, defender, false, { actionName: 'キングプレス', damageMultiplier: 2.0, isMagic: false, damageType: 'skill' }); } }, { name: '王の号令', chance: 20, description: 'ランダムな下位スライムを2体召喚する。', execute: createSummonAction('王の号令', ['slime_blue', 'slime_green', 'slime_red', 'slime_water', 'slime_fire', 'slime_ice', 'slime_wind', 'slime_thunder', 'slime_flower'], () => MONSTERS) }] },
  { id: 'slime_angel_king', name: 'エンジェルキングスライム', stats: { hp: 3180, atk: 179, def:  44, matk: 179, mdef:  44, spd:  35 }      , elements: { light:  50, dark: -50                }, ailments: { silence: 10   }        , rewards: { exp: 50, jp: 50, gold: 50 }  , drops: [{ itemId: 'slime_angel_king_jelly',  rate:   5 }, { itemId: 'slime_angel_king_core',   rate:   1 }, { itemId: 'slime_angel_king_fluid',  rate: 0.1 }], actions: [{ name: 'エンジェルブレス', chance: 15, description: '光属性の強力な魔法攻撃。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; attacker.stats.attackElements = { light: 100 }; battle.executeAttack(attacker, defender, false, { actionName: 'エンジェルブレス', damageMultiplier: 1.8, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; } }, { name: '天の導き', chance: 20, description: 'ダークスライムかエンジェルスライムをランダムに2体召喚する。', execute: createSummonAction('天の導き', ['slime_dark', 'slime_angel'], () => MONSTERS) }] },

  { id: 'spider_cave'     , name: 'ケイブスパイダー'        , stats: { hp:  399, atk: 158, def:  11, matk: 158, mdef:  11, spd:  44 }, elements: { dark:  50, light: -50 }       , ailments: { poison: 10 }          , rewards: { exp: 8, jp: 8, gold: 8 }, drops: [{ itemId: 'spider_cave_silk', rate: 5 }, { itemId: 'spider_cave_fang', rate: 1 }, { itemId: 'spider_cave_venom', rate: 0.1 }]                        , actions: [{ name: '暗闇からの強襲', chance: 30, description: '自身の攻撃力を一時的に1.5倍に引き上げてから強力な物理攻撃を行う。', execute: (attacker, defender, battle) => { const origAtk = attacker.stats.atk; attacker.stats.atk = Math.floor(origAtk * 1.5); battle.executeAttack(attacker, defender, false, { actionName: '暗闇からの強襲', damageMultiplier: 1.0, isMagic: false, damageType: 'skill' }); attacker.stats.atk = origAtk; } }] },
  { id: 'spider_poison'   , name: 'ポイズンスパイダー'      , stats: { hp:  420, atk: 172, def:  12, matk: 172, mdef:  12, spd:  46 }, elements: { dark:  50, light: -50 }      , ailments: { poison: 20 }           , rewards: { exp: 9, jp: 9, gold: 9 }, drops: [{ itemId: 'spider_poison_silk', rate: 5 }, { itemId: 'spider_poison_fang', rate: 1 }, { itemId: 'spider_poison_venom', rate: 0.1 }]                  , actions: [{ name: '劇毒の注入', chance: 30, description: '物理ダメージを与えつつ、さらに対象のMPにも直接ダメージを与える。', execute: (attacker, defender, battle) => { battle.executeAttack(attacker, defender, false, { actionName: '劇毒の注入', damageMultiplier: 1.2, isMagic: false, damageType: 'skill' }); if (!defender.isDead && defender.mp) { const mpDamage = Math.floor(attacker.stats.atk * 0.5); defender.mp.current = Math.max(0, defender.mp.current - mpDamage); battle.showDamage(defender.elementId, `MP -${mpDamage}`, 'text-blue-400'); } } }] },
  { id: 'spider_trapdoor' , name: 'トラップドアスパイダー'  , stats: { hp:  518, atk: 187, def:  15, matk: 187, mdef:  15, spd:  49 }, elements: { earth: 50, wind: -50 }       , ailments: { paralysis: 10 }        , rewards: { exp: 10, jp: 10, gold: 10 }, drops: [{ itemId: 'spider_trapdoor_silk', rate: 5 }, { itemId: 'spider_trapdoor_fang', rate: 1 }, { itemId: 'spider_trapdoor_venom', rate: 0.1 }]            , actions: [{ name: '引きずり込み', chance: 30, description: '物理ダメージを与えつつ、対象のATBを大きく減少させて行動を遅らせる。', execute: (attacker, defender, battle) => { battle.executeAttack(attacker, defender, false, { actionName: '引きずり込み', damageMultiplier: 1.2, isMagic: false, damageType: 'skill' }); if (!defender.isDead) { defender.atb = Math.max(0, defender.atb - 300); battle.showActionName(defender.elementId, 'ATB DOWN', 'text-yellow-400', 'border-yellow-500/50'); } } }] },
  { id: 'weaver_web'      , name: 'ウェブウィーバー'        , stats: { hp:  490, atk: 203, def:  14, matk: 203, mdef:  14, spd:  51 }, elements: { wind:  50, earth: -50 }      , ailments: { sleep: 10 }            , rewards: { exp: 12, jp: 12, gold: 12 }, drops: [{ itemId: 'weaver_web_silk', rate: 5 }, { itemId: 'weaver_web_fang', rate: 1 }, { itemId: 'weaver_web_venom', rate: 0.1 }]                           , actions: [{ name: '粘着糸の網', chance: 30, description: 'ダメージはないが、パーティ全員のATBを0にリセットする。', execute: (attacker, defender, battle) => { battle.showActionName(attacker.elementId, '粘着糸の網', 'text-purple-300', 'border-purple-500/50'); battle.party.forEach(p => { if (!p.isDead) { p.atb = 0; battle.showActionName(p.elementId, 'ATB RESET', 'text-yellow-400', 'border-yellow-500/50'); } }); } }] },
  { id: 'spitter_acid'    , name: 'アシッドスピッター'      , stats: { hp:  532, atk: 219, def:  15, matk: 219, mdef:  15, spd:  45 }, elements: { water: 50, thunder: -50 }    , ailments: { poison: 30 }           , rewards: { exp: 16, jp: 12, gold: 12 }, drops: [{ itemId: 'spitter_acid_silk', rate: 5 }, { itemId: 'spitter_acid_fang', rate: 1 }, { itemId: 'spitter_acid_venom', rate: 0.1 }]                     , actions: [{ name: 'アシッドシャワー', chance: 30, description: '水属性の魔法攻撃に加え、対象の現在HPの10%分の追加ダメージを与える。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; attacker.stats.attackElements = { water: 100 }; battle.executeAttack(attacker, defender, false, { actionName: 'アシッドシャワー', damageMultiplier: 1.0, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; if (!defender.isDead) { const hpDamage = Math.max(1, Math.floor(defender.currentHp * 0.1)); defender.currentHp = Math.max(1, defender.currentHp - hpDamage); battle.showDamage(defender.elementId, hpDamage, 'text-purple-400'); } } }] },
  { id: 'arachnid_shadow' , name: 'シャドウアラクニド'      , stats: { hp:  644, atk: 234, def:  18, matk: 234, mdef:  18, spd:  56 }, elements: { dark:  50, light: -50 }      , ailments: { blind: 20 }            , rewards: { exp: 18, jp: 14, gold: 15 } , drops: [{ itemId: 'arachnid_shadow_silk', rate: 5 }, { itemId: 'arachnid_shadow_fang', rate: 1 }, { itemId: 'arachnid_shadow_venom', rate: 0.1 }]            , actions: [{ name: 'シャドウステップ', chance: 30, description: '物理攻撃を行った後、瞬時に自身のATBを半分回復して次の行動を早める。', execute: (attacker, defender, battle) => { battle.executeAttack(attacker, defender, false, { actionName: 'シャドウステップ', damageMultiplier: 1.2, isMagic: false, damageType: 'skill' }); if (!attacker.isDead) { attacker.atb = Math.min(1000, (attacker.atb || 0) + 500); battle.showActionName(attacker.elementId, 'ATB UP', 'text-yellow-300', 'border-yellow-500/50'); } } }] },
  { id: 'tick_blood'      , name: 'ブラッドティック'        , stats: { hp:  616, atk: 250, def:  18, matk: 250, mdef:  18, spd:  49 }, elements: { water: 50, fire: -50 }       , ailments: { }                      , rewards: { exp: 16, jp: 13, gold: 12 } , drops: [{ itemId: 'tick_blood_silk', rate: 5 }, { itemId: 'tick_blood_fang', rate: 1 }, { itemId: 'tick_blood_venom', rate: 0.1 }]                           , actions: [{ name: '吸血の渇き', chance: 30, description: '対象のHPが半分以下の時にダメージが2倍になり、与えたダメージの半分を吸収して回復する。', execute: (attacker, defender, battle) => { const isWeak = defender.currentHp <= (defender.maxHp * 0.5); const multiplier = isWeak ? 2.4 : 1.2; const prevHp = defender.currentHp; battle.executeAttack(attacker, defender, false, { actionName: '吸血の渇き', damageMultiplier: multiplier, isMagic: false, damageType: 'skill' }); const damageDealt = prevHp - defender.currentHp; if (damageDealt > 0 && !attacker.isDead) { const heal = Math.floor(damageDealt * 0.5); attacker.currentHp = Math.min(attacker.stats.hp, attacker.currentHp + heal); battle.showDamage(attacker.elementId, `+${heal}`, 'text-green-400'); } } }] },
  { id: 'crawler_bone'    , name: 'ボーンクロウラー'        , stats: { hp:  658, atk: 266, def:  19, matk: 266, mdef:  19, spd:  51 }, elements: { earth: 50, wind: -50 }       , ailments: { curse: 10 }            , rewards: { exp: 15, jp: 13, gold: 18 } , drops: [{ itemId: 'crawler_bone_silk', rate: 5 }, { itemId: 'crawler_bone_fang', rate: 1 }, { itemId: 'crawler_bone_venom', rate: 0.1 }]                     , actions: [{ name: '骨の檻', chance: 30, description: 'パーティ全体に物理ダメージを与え、高確率で呪いを付与する。', execute: (attacker, defender, battle) => { battle.showActionName(attacker.elementId, '骨の檻', 'text-gray-300', 'border-gray-500/50'); const origA = attacker.stats.attackAilments; attacker.stats.attackAilments = { ...(origA || {}), curse: 40 }; battle.party.forEach(p => { if (!p.isDead) { battle.executeAttack(attacker, p, false, { actionName: '骨の檻', damageMultiplier: 0.8, isMagic: false, damageType: 'skill', hideActionName: true }); } }); attacker.stats.attackAilments = origA; } }] },
  { id: 'swarm_spider'    , name: 'スパイダースウォーム'    , stats: { hp:  805, atk: 282, def:  23, matk: 282, mdef:  23, spd:  64 }, elements: { wind:  50, earth: -50 }      , ailments: { poison: 10 }           , rewards: { exp: 17, jp: 14, gold: 15 } , drops: [{ itemId: 'swarm_spider_silk', rate: 5 }, { itemId: 'swarm_spider_fang', rate: 1 }, { itemId: 'swarm_spider_venom', rate: 0.1 }]                     , actions: [{ name: '無数の噛みつき', chance: 30, description: '生存しているランダムな対象に3回〜5回の連続攻撃を行う。', execute: (attacker, defender, battle) => { battle.showActionName(attacker.elementId, '無数の噛みつき', 'text-red-300', 'border-red-500/50'); const hits = 3 + Math.floor(Math.random() * 3); for (let i=0; i<hits; i++) { const aliveParty = battle.party.filter(p => !p.isDead); if (aliveParty.length === 0) break; const target = aliveParty[Math.floor(Math.random() * aliveParty.length)]; battle.executeAttack(attacker, target, false, { actionName: '噛みつき', damageMultiplier: 0.4, isMagic: false, damageType: 'skill', hideActionName: true }); } } }] },
  { id: 'spider_dark'     , name: 'ダークウィドウ'          , stats: { hp:  777, atk: 297, def:  23, matk: 297, mdef:  23, spd:  67 }, elements: { dark:  50, light: -50 }      , ailments: { curse: 20 }            , rewards: { exp: 22, jp: 18, gold: 19 } , drops: [{ itemId: 'spider_dark_silk', rate: 5 }, { itemId: 'spider_dark_fang', rate: 1 }, { itemId: 'spider_dark_venom', rate: 0.1 }]                        , actions: [{ name: '死の口づけ', chance: 30, description: '強力な闇属性魔法攻撃。この攻撃で対象を倒した場合、自身のHPを全回復する。', execute: (attacker, defender, battle) => { const origE = attacker.stats.attackElements; attacker.stats.attackElements = { dark: 100 }; battle.executeAttack(attacker, defender, false, { actionName: '死の口づけ', damageMultiplier: 1.5, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; if (defender.isDead && !attacker.isDead) { const heal = attacker.stats.hp - attacker.currentHp; attacker.currentHp = attacker.stats.hp; battle.showDamage(attacker.elementId, `+${heal}`, 'text-green-400'); } } }] },
  { id: 'weaver_golden'   , name: 'ゴールデンウィーバー'    , stats: { hp:  427, atk: 315, def:  50, matk: 315, mdef:  50, spd: 104 }, elements: { light: 50, dark: -50 }       , ailments: { paralysis: 20 }        , rewards: { exp: 7, jp: 8, gold: 84 }  , drops: [{ itemId: 'weaver_golden_silk', rate: 5 }, { itemId: 'weaver_golden_fang', rate: 1 }, { itemId: 'weaver_golden_venom', rate: 0.1 }]                  , actions: [{ name: '黄金の輝き', chance: 30, description: '生存している全ての味方のHPを最大値の20%回復する。', execute: (attacker, defender, battle) => { battle.showActionName(attacker.elementId, '黄金の輝き', 'text-yellow-300', 'border-yellow-500/50'); battle.enemies.forEach(e => { if (!e.isDead) { const heal = Math.floor(e.stats.hp * 0.2); e.currentHp = Math.min(e.stats.hp, e.currentHp + heal); battle.showDamage(e.elementId, `+${heal}`, 'text-green-400'); } }); } }] },
  { id: 'arachnid_crystal', name: 'クリスタルアラクニド'    , stats: { hp:  518, atk: 331, def:  61, matk: 331, mdef:  61, spd: 107 }, elements: { light: 50, dark: -50 }       , ailments: { blind: 30 }            , rewards: { exp: 30, jp: 13, gold: 8 }  , drops: [{ itemId: 'arachnid_crystal_silk', rate: 5 }, { itemId: 'arachnid_crystal_fang', rate: 1 }, { itemId: 'arachnid_crystal_venom', rate: 0.1 }]         , actions: [{ name: 'クリスタルプリズム', chance: 30, description: '全属性からランダムに1つの属性が選ばれる強力な魔法攻撃。', execute: (attacker, defender, battle) => { const elements = ['fire', 'water', 'grass', 'thunder', 'ice', 'wind', 'light', 'dark']; const el = elements[Math.floor(Math.random() * elements.length)]; const origE = attacker.stats.attackElements; attacker.stats.attackElements = { [el]: 100 }; battle.executeAttack(attacker, defender, false, { actionName: 'クリスタルプリズム', damageMultiplier: 1.5, isMagic: true, damageType: 'skill' }); attacker.stats.attackElements = origE; } }] },
  { id: 'boss_broodmother', name: 'ブルードマザー'          , stats: { hp: 4470, atk: 441, def:  62, matk: 441, mdef:  62, spd:  62 }, elements: { dark:  50, light: -50 }      , ailments: { poison: 50 }           , rewards: { exp: 53, jp: 43, gold: 38 }  , drops: [{ itemId: 'boss_broodmother_silk', rate: 5 }, { itemId: 'boss_broodmother_fang', rate: 1 }, { itemId: 'boss_broodmother_venom', rate: 0.1 }]         , actions: [{ name: 'クイーンズ・オーダー', chance: 40, description: 'スパイダースウォームを2体召喚し、さらに生存している全ての味方のATBをMAXにする。', execute: (attacker, defender, battle) => { createSummonAction('クイーンズ・オーダー', ['swarm_spider'], () => MONSTERS)(attacker, defender, battle); battle.enemies.forEach(e => { if (!e.isDead) e.atb = 1000; }); } }] },
  { id: 'boss_arachne'    , name: 'アラクネ・クイーン'      , stats: { hp: 5100, atk: 479, def:  71, matk: 479, mdef:  71, spd:  64 }, elements: { dark:  50, light: -50 }      , ailments: { curse: 50 }            , rewards: { exp: 67, jp: 46, gold: 52 }  , drops: [{ itemId: 'boss_arachne_silk', rate: 5 }, { itemId: 'boss_arachne_fang', rate: 1 }, { itemId: 'boss_arachne_venom', rate: 0.1 }]                     , actions: [{ name: '死の繭', chance: 40, description: '対象1体のHPを強制的に1にし、高確率で睡眠を付与する。', execute: (attacker, defender, battle) => { battle.showActionName(attacker.elementId, '死の繭', 'text-gray-300', 'border-gray-500/50'); if (!defender.isDead) { const dmg = defender.currentHp - 1; defender.currentHp = 1; if (dmg > 0) battle.showDamage(defender.elementId, dmg, 'text-purple-400'); const origA = attacker.stats.attackAilments; attacker.stats.attackAilments = { ...(origA || {}), sleep: 80 }; battle.executeAttack(attacker, defender, false, { actionName: '死の繭', damageMultiplier: 0, isMagic: true, damageType: 'skill', hideActionName: true }); attacker.stats.attackAilments = origA; } } }] },
  { id: 'boss_deathweaver', name: 'デスウィーバー'          , stats: { hp: 6330, atk: 521, def:  88, matk: 521, mdef:  88, spd:  79 }, elements: { dark:  50, light: -50 }      , ailments: { curse: 50, poison: 50 }, rewards: { exp: 103, jp: 120, gold: 11 } , drops: [{ itemId: 'boss_deathweaver_silk', rate: 5 }, { itemId: 'boss_deathweaver_fang', rate: 1 }, { itemId: 'boss_deathweaver_venom', rate: 0.1 }]         , actions: [{ name: '死神の糸', chance: 50, description: 'パーティ全体への闇属性魔法攻撃。対象のHPが30%以下の時、50%の確率で即死させる。', execute: (attacker, defender, battle) => { battle.showActionName(attacker.elementId, '死神の糸', 'text-red-500', 'border-red-600/50'); const origE = attacker.stats.attackElements; attacker.stats.attackElements = { dark: 100 }; battle.party.forEach(p => { if (!p.isDead) { battle.executeAttack(attacker, p, false, { actionName: '死神の糸', damageMultiplier: 1.5, isMagic: true, damageType: 'skill', hideActionName: true }); if (!p.isDead && p.currentHp <= (p.maxHp * 0.3)) { if (Math.random() < 0.5) { battle.showActionName(p.elementId, '即死', 'text-red-500', 'border-red-600/50'); battle.executeAttack(attacker, p, false, { actionName: '即死', damageMultiplier: 9999, isMagic: true, damageType: 'skill', hideActionName: true }); } } } }); attacker.stats.attackElements = origE; } }] }
].map(item => ({ ...item, image: `./assets/monster/${item.id}.webp` }));