/**
 * このファイルは敵として登場するモンスターの強さや、落とすアイテムなどのデータをまとめたファイルです。
 * 
 * モンスターのデータ定義ファイル
 * 
 * 敵キャラクターとして出現するモンスターのステータスやドロップアイテムを定義します。
 * 
 * テンプレート（各項目は省略可能、省略された値は 0 として扱われます）
 *    stats:         { hp: 0, atk: 0, def: 0, matk: 0, mdef: 0, spd: 0 },
 *    elements:      { fire: 0, water: 0, grass: 0, ice: 0, thunder: 0, wind: 0, earth: 0, light: 0, dark: 0 },
 *    ailments:      { poison: 0, burn: 0, paralysis: 0, sleep: 0, confusion: 0, curse: 0, blind: 0, silence: 0 },
 */

import { createElementalAttack, createSummonAction, createAilmentAttack } from './monster-helpers.js';

export const MONSTERS = [
  { id: 'slime_blue',       name: 'ブルースライム',           stats: { hp:  10, atk:  5, def:  1, matk:  5, mdef:  5, spd:  1 }, elements: { water:  50, thunder: -50, grass: -50 }, ailments: {               }, rewards: { exp:  1, jp:  1, gold:  1 }, drops: [{ itemId: 'slime_blue_jelly',        rate:   5 }, { itemId: 'slime_blue_core',         rate:   1 }, { itemId: 'slime_blue_fluid',        rate: 0.1 }], actions: [{ name: 'ウォーターアタック', chance: 10, execute: createElementalAttack('water', 'ウォーターアタック') }] },
  { id: 'slime_green',      name: 'グリーンスライム',         stats: { hp:  20, atk:  8, def:  5, matk:  9, mdef:  8, spd:  5 }, elements: { grass:  50, fire: -50                }, ailments: { poison: 10    }, rewards: { exp:  1, jp:  1, gold:  1 }, drops: [{ itemId: 'slime_green_jelly',       rate:   5 }, { itemId: 'slime_green_core',        rate:   1 }, { itemId: 'slime_green_fluid',       rate: 0.1 }], actions: [{ name: 'グラスアタック',     chance: 10, execute: createElementalAttack('grass', 'グラスアタック') }] },
  { id: 'slime_red',        name: 'レッドスライム',           stats: { hp:  30, atk: 14, def: 12, matk: 15, mdef: 10, spd:  8 }, elements: { fire:  50, water: -50                }, ailments: { burn: 10      }, rewards: { exp:  2, jp:  2, gold:  2 }, drops: [{ itemId: 'slime_red_jelly',         rate:   5 }, { itemId: 'slime_red_core',          rate:   1 }, { itemId: 'slime_red_fluid',         rate: 0.1 }], actions: [{ name: 'ファイアアタック', chance: 10, execute: createElementalAttack('fire', 'ファイアアタック') }] },
  { id: 'slime_water',      name: 'ウォータースライム',       stats: { hp:  40, atk: 17, def: 14, matk: 18, mdef: 12, spd:  9 }, elements: { water:  50, thunder: -50, grass: -50 }, ailments: {               }, rewards: { exp:  3, jp:  2, gold:  2 }, drops: [{ itemId: 'slime_water_jelly',       rate:   5 }, { itemId: 'slime_water_core',        rate:   1 }, { itemId: 'slime_water_fluid',       rate: 0.1 }], actions: [{ name: 'ウォーターアタック', chance: 10, execute: createElementalAttack('water', 'ウォーターアタック') }] },
  { id: 'slime_fire',       name: 'ファイヤースライム',       stats: { hp:  50, atk: 20, def: 16, matk: 21, mdef: 14, spd: 10 }, elements: { fire:  50, water: -50                }, ailments: { burn: 10      }, rewards: { exp:  3, jp:  2, gold:  3 }, drops: [{ itemId: 'slime_fire_jelly',        rate:   5 }, { itemId: 'slime_fire_core',         rate:   1 }, { itemId: 'slime_fire_fluid',        rate: 0.1 }], actions: [{ name: 'ファイアアタック', chance: 10, execute: createElementalAttack('fire', 'ファイアアタック') }] },
  { id: 'slime_ice',        name: 'アイススライム',           stats: { hp:  60, atk: 23, def: 18, matk: 24, mdef: 16, spd: 11 }, elements: { ice:  50, fire: -50                  }, ailments: { paralysis: 10 }, rewards: { exp:  4, jp:  3, gold:  4 }, drops: [{ itemId: 'slime_ice_jelly',         rate:   5 }, { itemId: 'slime_ice_core',          rate:   1 }, { itemId: 'slime_ice_fluid',         rate: 0.1 }], actions: [{ name: 'アイスアタック',     chance: 10, execute: createElementalAttack('ice', 'アイスアタック') }] },
  { id: 'slime_wind',       name: 'ウインドスライム',         stats: { hp:  72, atk: 27, def: 20, matk: 28, mdef: 18, spd: 15 }, elements: { wind:  50, ice: -50                  }, ailments: { blind: 10     }, rewards: { exp:  4, jp:  3, gold:  4 }, drops: [{ itemId: 'slime_wind_jelly',        rate:   5 }, { itemId: 'slime_wind_core',         rate:   1 }, { itemId: 'slime_wind_fluid',        rate: 0.1 }], actions: [{ name: 'ウィンドアタック', chance: 10, execute: createElementalAttack('wind', 'ウィンドアタック') }] },
  { id: 'slime_thunder',    name: 'サンダースライム',         stats: { hp:  85, atk: 31, def: 23, matk: 32, mdef: 21, spd: 16 }, elements: { thunder:  50, earth: -50             }, ailments: { paralysis: 10 }, rewards: { exp:  5, jp:  3, gold:  5 }, drops: [{ itemId: 'slime_thunder_jelly',     rate:   5 }, { itemId: 'slime_thunder_core',      rate:   1 }, { itemId: 'slime_thunder_fluid',     rate: 0.1 }], actions: [{ name: 'サンダーアタック', chance: 10, execute: createElementalAttack('thunder', 'サンダーアタック') }] },
  { id: 'slime_flower',     name: 'フラワースライム',         stats: { hp: 100, atk: 36, def: 26, matk: 37, mdef: 24, spd: 18 }, elements: { grass:  50, fire: -50                }, ailments: { sleep: 10     }, rewards: { exp:  5, jp:  3, gold:  6 }, drops: [{ itemId: 'slime_flower_jelly',      rate:   5 }, { itemId: 'slime_flower_core',       rate:   1 }, { itemId: 'slime_flower_fluid',      rate: 0.1 }], actions: [{ name: 'グラスアタック',     chance: 10, execute: createElementalAttack('grass', 'グラスアタック') }] },
  { id: 'slime_grass',      name: 'グラススライム',           stats: { hp: 115, atk: 41, def: 29, matk: 42, mdef: 27, spd: 15 }, elements: { grass:  50, fire: -50                }, ailments: { poison: 10    }, rewards: { exp:  8, jp:  2, gold: 30 }, drops: [{ itemId: 'slime_grass_jelly',       rate:   5 }, { itemId: 'slime_grass_core',        rate:   1 }, { itemId: 'slime_grass_fluid',       rate: 0.1 }], actions: [{ name: 'グラスアタック',     chance: 10, execute: createElementalAttack('grass', 'グラスアタック') }] },
  { id: 'slime_dark',       name: 'ダークスライム',           stats: { hp: 130, atk: 46, def: 32, matk: 47, mdef: 30, spd: 24 }, elements: { dark:  50, light: -50                }, ailments: { curse: 10     }, rewards: { exp:  8, jp:  4, gold:  7 }, drops: [{ itemId: 'slime_dark_jelly',        rate:   5 }, { itemId: 'slime_dark_core',         rate:   1 }, { itemId: 'slime_dark_fluid',        rate: 0.1 }], actions: [{ name: 'ダークアタック',     chance: 10, execute: createElementalAttack('dark', 'ダークアタック') }] },
  { id: 'slime_earth',      name: 'アーススライム',           stats: { hp: 148, atk: 52, def: 36, matk: 53, mdef: 34, spd: 17 }, elements: { earth:  50, wind: -50, grass: -50    }, ailments: {               }, rewards: { exp: 26, jp:  2, gold: 42 }, drops: [{ itemId: 'slime_earth_jelly',       rate:   5 }, { itemId: 'slime_earth_core',        rate:   1 }, { itemId: 'slime_earth_fluid',       rate: 0.1 }], actions: [{ name: 'アースアタック',     chance: 10, execute: createElementalAttack('earth', 'アースアタック') }] },
  { id: 'slime_angel',      name: 'エンジェルスライム',       stats: { hp: 168, atk: 58, def: 40, matk: 60, mdef: 38, spd: 25 }, elements: { light:  50, dark: -50                }, ailments: { silence: 10   }, rewards: { exp: 10, jp: 10, gold: 10 }, drops: [{ itemId: 'slime_angel_jelly',       rate:   5 }, { itemId: 'slime_angel_core',        rate:   1 }, { itemId: 'slime_angel_fluid',       rate: 0.1 }], actions: [{ name: 'ホーリーアタック', chance: 10, execute: createElementalAttack('light', 'ホーリーアタック') }] },
  { id: 'slime_king',       name: 'キングスライム',           stats: { hp: 250, atk: 70, def: 50, matk: 72, mdef: 48, spd: 38 }, elements: {                                      }, ailments: {               }, rewards: { exp: 10, jp: 10, gold: 10 }, drops: [{ itemId: 'slime_king_jelly',        rate:   5 }, { itemId: 'slime_king_core',         rate:   1 }, { itemId: 'slime_king_fluid',        rate: 0.1 }], actions: [{ name: 'スライム呼び', chance: 20, execute: createSummonAction('スライム呼び', ['slime_blue', 'slime_green', 'slime_red', 'slime_water', 'slime_fire', 'slime_ice', 'slime_wind', 'slime_thunder', 'slime_flower'], () => MONSTERS) }] },
  { id: 'slime_angel_king', name: 'エンジェルキングスライム', stats: { hp: 550, atk: 85, def: 60, matk: 88, mdef: 58, spd: 52 }, elements: { light:  50, dark: -50                }, ailments: { silence: 10   }, rewards: { exp: 20, jp: 20, gold: 20 }, drops: [{ itemId: 'slime_angel_king_jelly',  rate:   5 }, { itemId: 'slime_angel_king_core',   rate:   1 }, { itemId: 'slime_angel_king_fluid',  rate: 0.1 }], actions: [{ name: 'スライム呼び', chance: 20, execute: createSummonAction('スライム呼び', ['slime_dark', 'slime_angel'], () => MONSTERS) }] },

 { id: 'spider_cave',         name: 'ケイブスパイダー',          stats: { hp:  300, atk:  75, def:  55, matk:  75, mdef:  55, spd:  45 },     elements: { dark:  50, light: -50 }, ailments: { poison: 10 },    rewards: { exp:  50, jp:  10, gold:  50 }, drops: [{ itemId: 'spider_cave_silk', rate: 5 }, { itemId: 'spider_cave_fang', rate: 1 }, { itemId: 'spider_cave_venom', rate: 0.1 }],       actions: [{ name: '猛毒の牙', chance: 30, execute: createAilmentAttack('poison', 40, '猛毒の牙') }] },
 { id: 'spider_poison',       name: 'ポイズンスパイダー',        stats: { hp:  320, atk:  80, def:  60, matk:  80, mdef:  60, spd:  48 },     elements: { dark:  50, light: -50 }, ailments: { poison: 20 },    rewards: { exp:  60, jp:  12, gold:  60 }, drops: [{ itemId: 'spider_poison_silk', rate: 5 }, { itemId: 'spider_poison_fang', rate: 1 }, { itemId: 'spider_poison_venom', rate: 0.1 }], actions: [{ name: '猛毒の牙', chance: 30, execute: createAilmentAttack('poison', 50, '猛毒の牙') }] },
 { id: 'spider_trapdoor',     name: 'トラップドアスパイダー',    stats: { hp:  350, atk:  85, def:  65, matk:  85, mdef:  65, spd:  50 },     elements: { earth: 50, wind: -50 },  ailments: { paralysis: 10 }, rewards: { exp:  70, jp:  14, gold:  70 }, drops: [{ itemId: 'spider_trapdoor_silk', rate: 5 }, { itemId: 'spider_trapdoor_fang', rate: 1 }, { itemId: 'spider_trapdoor_venom', rate: 0.1 }], actions: [{ name: '麻痺の牙', chance: 30, execute: createAilmentAttack('paralysis', 40, '麻痺の牙') }] },
 { id: 'weaver_web',          name: 'ウェブウィーバー',          stats: { hp:  380, atk:  90, def:  70, matk:  90, mdef:  70, spd:  55 },     elements: { wind:  50, earth: -50 }, ailments: { sleep: 10 },     rewards: { exp:  80, jp:  16, gold:  80 }, drops: [{ itemId: 'weaver_web_silk', rate: 5 }, { itemId: 'weaver_web_fang', rate: 1 }, { itemId: 'weaver_web_venom', rate: 0.1 }],          actions: [{ name: '眠りの糸', chance: 30, execute: createAilmentAttack('sleep', 40, '眠りの糸') }] },
 { id: 'spitter_acid',        name: 'アシッドスピッター',        stats: { hp:  400, atk:  95, def:  75, matk:  95, mdef:  75, spd:  58 },     elements: { water: 50, thunder: -50 }, ailments: { poison: 30 },    rewards: { exp:  90, jp:  18, gold:  90 }, drops: [{ itemId: 'spitter_acid_silk', rate: 5 }, { itemId: 'spitter_acid_fang', rate: 1 }, { itemId: 'spitter_acid_venom', rate: 0.1 }],    actions: [{ name: '猛毒の酸', chance: 30, execute: createAilmentAttack('poison', 60, '猛毒の酸') }] },
 { id: 'arachnid_shadow',     name: 'シャドウアラクニド',        stats: { hp:  420, atk: 100, def:  80, matk: 100, mdef:  80, spd:  62 },     elements: { dark:  50, light: -50 }, ailments: { blind: 20 },     rewards: { exp: 100, jp:  20, gold: 100 }, drops: [{ itemId: 'arachnid_shadow_silk', rate: 5 }, { itemId: 'arachnid_shadow_fang', rate: 1 }, { itemId: 'arachnid_shadow_venom', rate: 0.1 }], actions: [{ name: '暗闇の牙', chance: 30, execute: createAilmentAttack('blind', 50, '暗闇の牙') }] },
 { id: 'tick_blood',          name: 'ブラッドティック',          stats: { hp:  450, atk: 105, def:  85, matk: 105, mdef:  85, spd:  65 },     elements: { water: 50, fire: -50 },  ailments: { },               rewards: { exp: 110, jp:  22, gold: 110 }, drops: [{ itemId: 'tick_blood_silk', rate: 5 }, { itemId: 'tick_blood_fang', rate: 1 }, { itemId: 'tick_blood_venom', rate: 0.1 }],          actions: [{ name: '吸血毒', chance: 30, execute: createAilmentAttack('poison', 40, '吸血毒') }] },
 { id: 'crawler_bone',        name: 'ボーンクロウラー',          stats: { hp:  480, atk: 110, def:  90, matk: 110, mdef:  90, spd:  68 },     elements: { earth: 50, wind: -50 },  ailments: { curse: 10 },     rewards: { exp: 120, jp:  24, gold: 120 }, drops: [{ itemId: 'crawler_bone_silk', rate: 5 }, { itemId: 'crawler_bone_fang', rate: 1 }, { itemId: 'crawler_bone_venom', rate: 0.1 }],    actions: [{ name: '呪いの骨格', chance: 30, execute: createAilmentAttack('curse', 40, '呪いの骨格') }] },
 { id: 'swarm_spider',        name: 'スパイダースウォーム',      stats: { hp:  500, atk: 115, def:  95, matk: 115, mdef:  95, spd:  70 },     elements: { wind:  50, earth: -50 }, ailments: { poison: 10 },    rewards: { exp: 130, jp:  26, gold: 130 }, drops: [{ itemId: 'swarm_spider_silk', rate: 5 }, { itemId: 'swarm_spider_fang', rate: 1 }, { itemId: 'swarm_spider_venom', rate: 0.1 }],    actions: [{ name: '群れでの毒撃', chance: 30, execute: createAilmentAttack('poison', 40, '群れでの毒撃') }] },
 { id: 'spider_dark',         name: 'ダークウィドウ',            stats: { hp:  550, atk: 120, def: 100, matk: 120, mdef: 100, spd:  75 },     elements: { dark:  50, light: -50 }, ailments: { curse: 20 },     rewards: { exp: 150, jp:  30, gold: 150 }, drops: [{ itemId: 'spider_dark_silk', rate: 5 }, { itemId: 'spider_dark_fang', rate: 1 }, { itemId: 'spider_dark_venom', rate: 0.1 }],       actions: [{ name: '猛毒の呪い', chance: 30, execute: createAilmentAttack('poison', 60, '猛毒の呪い') }] },
 { id: 'weaver_golden',       name: 'ゴールデンウィーバー',      stats: { hp:  800, atk: 140, def: 120, matk: 140, mdef: 120, spd:  85 },     elements: { light: 50, dark: -50 },  ailments: { paralysis: 20 }, rewards: { exp: 500, jp: 100, gold: 1000 }, drops: [{ itemId: 'weaver_golden_silk', rate: 5 }, { itemId: 'weaver_golden_fang', rate: 1 }, { itemId: 'weaver_golden_venom', rate: 0.1 }], actions: [{ name: '黄金の麻痺糸', chance: 30, execute: createAilmentAttack('paralysis', 60, '黄金の麻痺糸') }] },
 { id: 'arachnid_crystal',    name: 'クリスタルアラクニド',      stats: { hp:  900, atk: 150, def: 130, matk: 150, mdef: 130, spd:  90 },     elements: { light: 50, dark: -50 },  ailments: { blind: 30 },     rewards: { exp: 600, jp: 120, gold: 1200 }, drops: [{ itemId: 'arachnid_crystal_silk', rate: 5 }, { itemId: 'arachnid_crystal_fang', rate: 1 }, { itemId: 'arachnid_crystal_venom', rate: 0.1 }], actions: [{ name: '暗闇の水晶', chance: 30, execute: createAilmentAttack('blind', 60, '暗闇の水晶') }] },
 { id: 'boss_broodmother',    name: 'ブルードマザー',            stats: { hp: 2000, atk: 200, def: 150, matk: 200, mdef: 150, spd: 100 },     elements: { dark:  50, light: -50 }, ailments: { poison: 50 },    rewards: { exp: 2000, jp: 500, gold: 3000 }, drops: [{ itemId: 'boss_broodmother_silk', rate: 5 }, { itemId: 'boss_broodmother_fang', rate: 1 }, { itemId: 'boss_broodmother_venom', rate: 0.1 }], actions: [{ name: '致命的な猛毒', chance: 40, execute: createAilmentAttack('poison', 100, '致命的な猛毒', 1.5) }, { name: '子蜘蛛召喚', chance: 20, execute: createSummonAction('子蜘蛛召喚', ['swarm_spider'], () => MONSTERS) }] },
 { id: 'boss_arachne',        name: 'アラクネ・クイーン',        stats: { hp: 3000, atk: 250, def: 180, matk: 250, mdef: 180, spd: 110 },     elements: { dark:  50, light: -50 }, ailments: { curse: 50 },     rewards: { exp: 3000, jp: 800, gold: 5000 }, drops: [{ itemId: 'boss_arachne_silk', rate: 5 }, { itemId: 'boss_arachne_fang', rate: 1 }, { itemId: 'boss_arachne_venom', rate: 0.1 }],    actions: [{ name: '女王の猛毒糸', chance: 40, execute: createAilmentAttack('poison', 100, '女王の猛毒糸', 1.8) }] },
 { id: 'boss_deathweaver',  name: 'デスウィーバー',             stats: { hp: 4500, atk: 300, def: 200, matk: 300, mdef: 200, spd: 120 }, elements: { dark:  50, light: -50 }, ailments: { curse: 50, poison: 50 }, rewards: { exp: 5000, jp: 1200, gold: 8000 }, drops: [{ itemId: 'boss_deathweaver_silk', rate: 5 }, { itemId: 'boss_deathweaver_fang', rate: 1 }, { itemId: 'boss_deathweaver_venom', rate: 0.1 }], actions: [{ name: '死の猛毒', chance: 50, execute: createAilmentAttack('poison', 100, '死の猛毒', 2.0) }] }
].map(item => ({ ...item, image: `./assets/monster/${item.id}.webp` }));